### ISSUE TITLE
Wrap code that gets executed when imported for platforms.py

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#101]
We have code that gets called simply by importing the library [1].
We should wrap those pieces of code so when we import platforms.py we don't execute it.
We should use private functions (i.e. starting with "_") and call those from the main functions.

https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/platforms.py#L16

**Comment by adusca** [comment]
I was experimenting with that this week, I have a half-ready version. I will finish it now.

**Comment by armenzg** [comment]
https://github.com/armenzg/mozilla_ci_tools/pull/103
