### ISSUE TITLE
"make livehtml" needs "make html" to be run first

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#107]
This can be easily noticed by removing _build if existent under docs, run 'make livehtml', load the localhost and you will get an empty page.

We should check if _build exists and call "make html" if missing.

**Comment by vaibhavmagarwal** [comment]
Working on this.

**Comment by vaibhavmagarwal** [comment]
Fixed in https://github.com/armenzg/mozilla_ci_tools/pull/108
