### ISSUE TITLE
Write script to trigger jobs missing on a try push - Use case #9

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#109]
In case scenario nine [1] we document a developer pushing to try with a specific try syntax and realizes that it is missing some other platforms he cares about.

When a developer pushes to try, they have to add "try syntax" [2] to their tipmost message. This commit message (e.g. try: -b do -p linux,macosx64,win32,win64 -u reftest,crashtest,xpcshell,mochitests -t none) is parsed by try_parser.py [3][4] and determines which list of builders will be triggered.
From the tests [5], we can see what expected values will be needed. A lot of those tests are rather out of date.

This is how I expect the script would be used:
* The developer has a push to try
* The developer calls the script with a URL to the try push
* The developer will pass a *new* trychooser commit message
* The script will validate that the syntax is correct
* The script will determine what builders get triggered with the *current* trychooser message
* The script will determine what builders get triggered with the *new* trychooser message
* The script will show the difference between the two lists and prompt the user
   * The options would be: a) trigger, b) try again with a different trychooser, c) exit

@mikeconley would this workflow work for you?

We would need to create a trychooser module that would help us do all mentioned above.
A possible name for the script could be change_my_try_syntax.py (easy to remember)

[1] http://mozilla-ci-tools.readthedocs.org/en/master/use_cases.html#case-scenario-9-we-generate-data-to-build-a-dynamic-trychooser-ui
[2] http://trychooser.pub.build.mozilla.org
[3] http://hg.mozilla.org/build/buildbotcustom/file/fbddb9e443cf/try_parser.py
[4] http://mxr.mozilla.org/build/source/buildbotcustom/misc_scheduler.py#23
[5] http://hg.mozilla.org/build/buildbotcustom/file/fbddb9e443cf/test/test_try_parser.py

**Comment by mikeconley** [comment]
Assuming that the script you're referring to is something I can invoke easily from, say, mach, then yes, this sounds perfectly fine to me. :)

**Comment by armenzg** [comment]
Filed issue #110 to add mach support. If you have any pointers we should put it there. Thanks Mike!

**Comment by vaibhavmagarwal** [comment]
Now that we have a prototype at http://try-extender.herokuapp.com/ , can we close this issue?

**Comment by armenzg** [comment]
Let's close this.

**Comment by armenzg** [comment]
This was fixed by adusca with the Try Extender.
