### ISSUE TITLE
mozci.py calls _status_summary which now returns 4 items

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#114]
ln 417:
successful_jobs = _status_summary(matching_jobs)

we really should have it be:
successful_jobs = _status_summary(matching_jobs)[0]

or maybe consider pending, coalesced, failed, etc. jobs

**Comment by armenzg** [comment]
Fixed:
https://github.com/armenzg/mozilla_ci_tools/commit/7b2feb10202be5a790be1c3825e879bcc09a51ab
