### ISSUE TITLE
Add --skip to commandline options in trigger_range.py

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#115]
@jmaher suggests that it will be useful to go back 15 revisions, but trigger every 3rd revision (so have 5 retriggers) with say 20 retriggers each. That would be 100 jobs per failure which is manageable and then we can narrow the window down assuming we find something.

This looks like a useful thing to do. I am working on this.

**Comment by armenzg** [comment]
Makes sense. Note that I would like to rename trigger_range.py to trigger.py (drop the old one).
When would you like me to land that change to make it less disrupting to you?

**Comment by vaibhavmagarwal** [comment]
@armenzg, I have uploaded the patch for this: https://github.com/armenzg/mozilla_ci_tools/pull/116/files
It is a short one, so you can land this change and then land yours on top of it.

**Comment by armenzg** [comment]
I will merge your changes. Thanks!
