### ISSUE TITLE
Gaia-try builders should be treated as build jobs

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#117]
gaia-try is very special; there are only upstream builders.

We should change platforms.py to be able to say that they are upstream builders and don't trigger any tests.

armenzg@armenzg-thinkpad:~/repos/bc.hg$ grep "gaia-try" all_builders.txt 
 u'b2g_ubuntu32_vm gaia-try opt test mochitest-1',
 u'b2g_ubuntu32_vm gaia-try opt test reftest-sanity',
 u'b2g_ubuntu64_vm gaia-try debug test gaia-ui-test-accessibility',
 u'b2g_ubuntu64_vm gaia-try debug test gaia-ui-test-functional-1',
 u'b2g_ubuntu64_vm gaia-try debug test gaia-ui-test-functional-2',
 u'b2g_ubuntu64_vm gaia-try debug test gaia-ui-test-functional-3',
 u'b2g_ubuntu64_vm gaia-try debug test gaia-ui-test-unit',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-build',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-build-unit',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-1',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-10',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-2',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-3',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-4',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-5',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-6',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-7',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-8',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-js-integration-9',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-linter',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-ui-test-accessibility',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-ui-test-functional-1',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-ui-test-functional-2',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-ui-test-functional-3',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-ui-test-unit',
 u'b2g_ubuntu64_vm gaia-try opt test gaia-unit',
 u'b2g_ubuntu64_vm gaia-try opt test mochitest-oop-1',
 u'b2g_ubuntu64_vm gaia-try opt test reftest-sanity-oop',

**Comment by adusca** [comment]
Should is_downstream return False for every gaia-try buildername?

**Comment by armenzg** [comment]
Correct.

**Comment by adusca** [comment]
Fixed on #133
