### ISSUE TITLE
alltalos doesn't ask for credentials

### ISSUE THREAD

**Issue by glandium** [armenzg/mozilla_ci_tools#118]
As I understand it, credentials are supposed to be prompted for. That doesn't happen for (at least) alltalos.

Traceback (most recent call last):
  File "scripts/alltalos.py", line 81, in <module>
    main()
  File "scripts/alltalos.py", line 78, in main
    dry_run=options.dry_run)
  File "build/bdist.linux-x86_64/egg/mozci/mozci.py", line 290, in trigger_job
  File "build/bdist.linux-x86_64/egg/mozci/mozci.py", line 213, in query_repo_name_from_buildername
  File "build/bdist.linux-x86_64/egg/mozci/sources/buildapi.py", line 213, in query_repositories
AssertionError: Authorization Required

**Comment by jmaher** [comment]
I assume this is related to all scripts, not just alltalos- it should ask for credentials, so good find!

**Comment by armenzg** [comment]
I removed my credentials file and I got prompted.
What was the exact command?
Are you on the latest code?

armenzg@armenzg-thinkpad:~/repos/ci_tools$ rm ~/.mozilla/credentials.cfg
armenzg@armenzg-thinkpad:~/repos/ci_tools$ python scripts/alltalos.py --repo-name cedar --rev default --dry-run --times 1
03/12/2015 09:42:48 INFO:	 We want to trigger 'Android 4.0 armv7 API 11+ cedar talos remote-tp4m_nochrome' on revision 'default' a total of 1 time(s).
Please enter your full LDAP email address:

**Comment by glandium** [comment]
The command was, as far as my bash history tells, python scripts/alltalos.py --repo-name try --times 2 --rev 921277f744d9
And I unfortunately can't reproduce anymore.

**Comment by armenzg** [comment]
Let's close it for now. Thanks for your report though!
