### ISSUE TITLE
It should be possible to never store credentials

### ISSUE THREAD

**Issue by glandium** [armenzg/mozilla_ci_tools#119]
mozci/utils/authentication.py will store credentials after prompting for them. There should be a way to avoid this from happening. I don't want my credentials to be written in plain text on disk.

**Comment by armenzg** [comment]
Would --always-prompt as an argument help? (or similar)

**Comment by jmaher** [comment]
it would be nice if we could store the 'username' and then input the password if it wasn't found.  maybe a .mozcirc file or something like that.

**Comment by armenzg** [comment]
Let us know what is your preference.

**Comment by glandium** [comment]
I think an option of some sort that would make get_credentials only store the username would be a good thing. That said, is it a good default to store the password?

**Comment by armenzg** [comment]
I've seen tools written by gps that does that (the one that posts into bugzilla).
We can make it non-default. This was very useful for me for development purposes.

**Comment by vaibhavmagarwal** [comment]
I'll take this one.

**Comment by vaibhavmagarwal** [comment]
I'll make storing and retrieving the password from the file as non-default, but still have it as an option in case someone like me does not want the hassle to input it always.

**Comment by adusca** [comment]
It would be cool to be able to store credentials in gnome-keyring. I have no idea if this is possible.

**Comment by armenzg** [comment]
I wish we found a module that did this for us.

**Comment by adusca** [comment]
python-keyring looks pretty nice, it even has cross-platform support for using the system's keyring: https://pypi.python.org/pypi/keyring

**Comment by vaibhavmagarwal** [comment]
Thanks @adusca. Added keyring support in https://github.com/armenzg/mozilla_ci_tools/pull/184
