### ISSUE TITLE
Alltalos should look at the try syntax OR at the list of existing build jobs to determine which downstream jobs we need to trigger (Only for try)

### ISSUE THREAD

**Issue by glandium** [armenzg/mozilla_ci_tools#121]
Related to issue #120, what I initially wanted to do is trigger 2 runs of every talos job *on the build that was already there, and not any other*.

**Comment by armenzg** [comment]
If this gets fixed with updating the checkout please let ys know.

**Comment by glandium** [comment]
This is still an issue:
05/29/2015 11:28:08 INFO:	 We want to trigger 'Android 4.0 armv7 API 11+ try talos remote-tp4m_nochrome' on revision '0c31667c79fa' a total of 5 time(s).
05/29/2015 11:28:49 INFO:	 We will trigger 1) 'Android armv7 API 11+ try build' instead of 2) 'Android 4.0 armv7 API 11+ try talos remote-tp4m_nochrome'
05/29/2015 11:28:49 INFO:	 We need to trigger the build job once (1) in order to be able to run the test job (2).
05/29/2015 11:28:49 INFO:	 You'll need to run the script again after (1) is done to trigger (2).
05/29/2015 11:28:49 INFO:	 In order to trigger Android 4.0 armv7 API 11+ try talos remote-tp4m_nochrome 5 times, please run the script again after Android armv7 API 11+ try build ends.
05/29/2015 11:28:49 INFO:	 Dry-run: We were going to request 'Android armv7 API 11+ try build' 1 times.
05/29/2015 11:28:49 INFO:	 Dry-run: We were going to request a job for 'Android armv7 API 11+ try build'

**Comment by armenzg** [comment]
I'm looking at https://treeherder.mozilla.org/#/jobs?repo=try&revision=0c31667c79fa
I only see Linux x64 jobs there, however, in your output you're talking about Android jobs.
I'm going to change the name of this issue to help me not get confused in the future.

For non-try repos, we should not follow this behaviour since, sometimes, there are builds which are skipped.

Poking @jmaher to be in the loop.

**Comment by armenzg** [comment]
I'm leaning towards the list of build jobs on a try push over the try syntax since we might have try pushes where developers have added more platforms post-push (i.e. for instance through mozci-trigger).

**Comment by glandium** [comment]
> I'm looking at https://treeherder.mozilla.org/#/jobs?repo=try&revision=0c31667c79fa
> I only see Linux x64 jobs there, however, in your output you're talking about Android jobs.

The output is from --dry-run and that's exactly the problem: it wants to start build jobs for everything that I didn't get build jobs for.

> For non-try repos, we should not follow this behaviour since, sometimes, there are builds which are skipped.

I'm not sure what you mean. IMHO, most of the time, you don't want to trigger talos jobs for more than what you have already build jobs for, whether on try or not.

**Comment by armenzg** [comment]
>> I'm looking at https://treeherder.mozilla.org/#/jobs?repo=try&revision=0c31667c79fa
>> I only see Linux x64 jobs there, however, in your output you're talking about Android jobs.
>
> The output is from --dry-run and that's exactly the problem: it wants to start build jobs for everything  that I didn't get build jobs for.

I was initially reading that if there is a talos job to schedule we schedule a build job *even* if there is already a build that had run. That is why I need to clarify the title a bit for myself.

>> For non-try repos, we should not follow this behaviour since, sometimes, there are builds which are skipped.
>
> I'm not sure what you mean. IMHO, most of the time, you don't want to trigger talos jobs for more than what you have already build jobs for, whether on try or not.

This is not the case for example for m-i where builds that would have triggered talos jobs were skipped.

**Comment by armenzg** [comment]
Fixed by @adusca in https://github.com/armenzg/mozilla_ci_tools/pull/228
To overwrite the try behaviour we can use --trigger-build-if-missing

**Comment by armenzg** [comment]
@adusca I would like to keep this open until we release and also to add the associated doc changes.
No rush on this. I will do a dot release either today or by Monday.

@glandium you can use the latest code until the release happens.
