### ISSUE TITLE
alltalos runs OSX 10.8 talos jobs that normally don't run

### ISSUE THREAD

**Issue by glandium** [armenzg/mozilla_ci_tools#123]
Using alltalos on 6c15cffac2e6, I got jobs started for 10.8 that are not run on inbound/central.

**Comment by jmaher** [comment]
this is hard as we just recently switched from 10.8 to 10.10.  alltalos looks for the list of builders for the given repo, and then builds a list of all related jobs.  what repo is 6c15cffac2e6 on?

**Comment by armenzg** [comment]
Could you please paste the command you used?
You can also run it with --debug and --dry-run which would give us a lot of info to work from.

armenzg@armenzg-thinkpad:~/repos/ci_tools$ grep "10.8" all_builders.txt | grep "talos"
 u'Rev5 MacOSX Mountain Lion 10.8 date talos chromez',
 u'Rev5 MacOSX Mountain Lion 10.8 date talos dromaeojs',
 u'Rev5 MacOSX Mountain Lion 10.8 date talos g1',
 u'Rev5 MacOSX Mountain Lion 10.8 date talos other_nol64',
 u'Rev5 MacOSX Mountain Lion 10.8 date talos svgr',
 u'Rev5 MacOSX Mountain Lion 10.8 date talos tp5o',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-aurora talos chromez',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-aurora talos dromaeojs',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-aurora talos g1',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-aurora talos other_nol64',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-aurora talos svgr',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-aurora talos tp5o',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-beta talos chromez',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-beta talos dromaeojs',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-beta talos g1',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-beta talos other_nol64',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-beta talos svgr',
 u'Rev5 MacOSX Mountain Lion 10.8 mozilla-beta talos tp5o',
 u'Rev5 MacOSX Mountain Lion 10.8 try talos chromez',
 u'Rev5 MacOSX Mountain Lion 10.8 try talos dromaeojs',
 u'Rev5 MacOSX Mountain Lion 10.8 try talos g1',
 u'Rev5 MacOSX Mountain Lion 10.8 try talos other_nol64',
 u'Rev5 MacOSX Mountain Lion 10.8 try talos svgr',
 u'Rev5 MacOSX Mountain Lion 10.8 try talos tp5o',

**Comment by armenzg** [comment]
I misunderstood this when I wrote my comment.

As jmaher points out, we are switching release branches to use 10.10 instead of 10.8.
We trigger what matters for that specific branch and we don't have the ability to run anything that buildbot does not have available for that repo.

Nothing to fix in here. Thanks for reporting!
http://relengofthenerds.blogspot.ca/2015/03/scaling-yosemite.html
