### ISSUE TITLE
determine_upstream_builder() should associate L10n builders to their associated nightly builder

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#124]
We currently fail to associate an L10n (aka localized - aka translated) jobs to the nightly job that triggers it. We need to adjust determine_upstream_builde() to account for this.

We might need to make adjustments to allthethings.json

* Example of nightly builders with associated L10n jobs
Android armv7 API 11+ mozilla-central nightly
Android armv7 API 9 mozilla-central nightly
Linux mozilla-central nightly
Linux x86-64 mozilla-central nightly
OS X 10.7 mozilla-central nightly
TB Linux comm-central nightly
TB Linux x86-64 comm-central nightly
TB OS X 10.7 comm-central nightly
TB WINNT 5.2 comm-central nightly
TB WINNT 6.1 x86-64 comm-central nightly
WINNT 5.2 mozilla-central nightly
WINNT 6.1 x86-64 mozilla-central nightly

* List of associated L10n jobs
Android armv7 API 11+ mozilla-central l10n nightly-1
Android armv7 API 11+ mozilla-central l10n nightly-2
Android armv7 API 11+ mozilla-central l10n nightly-3
Android armv7 API 11+ mozilla-central l10n nightly-4
Android armv7 API 11+ mozilla-central l10n nightly-5
Android armv7 API 9 mozilla-central l10n nightly-1
Android armv7 API 9 mozilla-central l10n nightly-2
Android armv7 API 9 mozilla-central l10n nightly-3
Android armv7 API 9 mozilla-central l10n nightly-4
Android armv7 API 9 mozilla-central l10n nightly-5
Firefox mozilla-central linux l10n nightly
Firefox mozilla-central linux64 l10n nightly
Firefox mozilla-central macosx64 l10n nightly
Firefox mozilla-central win32 l10n nightly
Firefox mozilla-central win64 l10n nightly
Thunderbird comm-central linux l10n nightly
Thunderbird comm-central linux64 l10n nightly
Thunderbird comm-central macosx64 l10n nightly
Thunderbird comm-central win32 l10n nightly

**Comment by armenzg** [comment]
With regards to L10n nightly jobs I have a bit of a debate.
We don't need a nightly job to be triggered for an L10n job to be triggered like test jobs are dependent to a build job.

When an L10n job happens, it is because a nightly job has completed.
However, if we trigger an L10n job, if I understand correctly, it will automatically find the location of the latest nightly build which has been uploaded [1].
This is why we don't need to specify "files" like the test jobs need.

If we trigger an L10n job, we should make sure that we don't trigger the associated nightly build but fail. This way, whoever decides in the future to trigger L10n jobs through mozci will need to come and talk with us with regards to the best behaviour to take (well, we currently fail as-is) [2]

[1] ftp://ftp.mozilla.org/pub/mozilla.org/mobile/nightly/latest-mozilla-central-android-api-9/en-US/
[2] armenzg@armenzg-thinkpad:~/repos/ci_tools$ python scripts/trigger_range.py --buildername "Thunderbird comm-central win32 l10n nightly" --revision default --dry-run
03/12/2015 11:01:39 INFO:	 We want to have 1 job(s) of Thunderbird comm-central win32 l10n nightly on revisions ['default']
03/12/2015 11:01:39 INFO:	 
03/12/2015 11:01:39 INFO:	 === default ===
03/12/2015 11:01:40 INFO:	 We want to have 1 job(s) of Thunderbird comm-central win32 l10n nightly on revision default
Please enter your full LDAP email address: armenzg@mozilla.com
Password: 
03/12/2015 11:01:53 INFO:	 We have found 0 potential job(s) matching 'Thunderbird comm-central win32 l10n nightly' on default. We need to trigger more.
03/12/2015 11:01:53 INFO:	 We want to trigger 'Thunderbird comm-central win32 l10n nightly' on revision 'default' a total of 1 time(s).
03/12/2015 11:01:56 ERROR:	 We didn't find a build job matching Thunderbird comm-central win32 l10n nightly
03/12/2015 11:01:56 ERROR:	 No build job found.
Traceback (most recent call last):
  File "scripts/trigger_range.py", line 170, in <module>
    dry_run=options.dry_run
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 380, in trigger_range
    dry_run=dry_run)
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 310, in trigger_job
    buildername,
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 71, in _determine_trigger_objective
    build_buildername = determine_upstream_builder(buildername)
  File "/home/armenzg/repos/ci_tools/mozci/platforms.py", line 117, in determine_upstream_builder
    raise Exception("No build job found.")
Exception: No build job found.

**Comment by adusca** [comment]
There was a wrong skip statement in platforms.py that cause this issue, but I removed in #112 . "Thunderbird comm-central win32 l10n nightly" is considered a build job, thought. Should it be considered a test job? It does not belong to any test scheduler in allthethings.json. Running now:

(venv)alice@alice-UX303LN:~/mozilla_ci_tools$ python scripts/trigger.py --buildername "Thunderbird comm-central win32 l10n nightly" --revision default --dry-run --debug
03/13/2015 08:34:42 INFO:	 Setting DEBUG level
03/13/2015 08:34:42 DEBUG:	 Loading /home/alice/mozilla_ci_tools/repositories.txt
03/13/2015 08:34:42 DEBUG:	 Determine repository associated to comm-central
03/13/2015 08:34:42 INFO:	 We want to have 1 job(s) of Thunderbird comm-central win32 l10n nightly on revisions ['default']
03/13/2015 08:34:42 INFO:	 
03/13/2015 08:34:42 INFO:	 === default ===
03/13/2015 08:34:42 DEBUG:	 Determine if the revision is valid for buildapi.
03/13/2015 08:34:42 DEBUG:	 Determine repository associated to comm-central
03/13/2015 08:34:42 DEBUG:	 About to fetch https://hg.mozilla.org/comm-central/json-pushes?changeset=default&tipsonly=1&full=1
03/13/2015 08:34:42 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/13/2015 08:34:44 DEBUG:	 "GET /comm-central/json-pushes?changeset=default&tipsonly=1&full=1 HTTP/1.1" 200 339
03/13/2015 08:34:44 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/13/2015 08:34:44 INFO:	 We want to have 1 job(s) of Thunderbird comm-central win32 l10n nightly on revision default
03/13/2015 08:34:44 DEBUG:	 Determine if the revision is valid for buildapi.
03/13/2015 08:34:44 DEBUG:	 Determine repository associated to comm-central
03/13/2015 08:34:44 DEBUG:	 About to fetch https://hg.mozilla.org/comm-central/json-pushes?changeset=default&tipsonly=1&full=1
03/13/2015 08:34:44 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/13/2015 08:34:45 DEBUG:	 "GET /comm-central/json-pushes?changeset=default&tipsonly=1&full=1 HTTP/1.1" 200 339
03/13/2015 08:34:45 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/13/2015 08:34:45 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/comm-central/rev/default?format=json
03/13/2015 08:34:45 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/13/2015 08:34:47 DEBUG:	 "GET /buildapi/self-serve/comm-central/rev/default?format=json HTTP/1.1" 200 919
03/13/2015 08:34:47 DEBUG:	 Find jobs matching 'Thunderbird comm-central win32 l10n nightly'
03/13/2015 08:34:47 DEBUG:	 We have found 0 job(s) of 'Thunderbird comm-central win32 l10n nightly'.
03/13/2015 08:34:47 DEBUG:	 We found 0 pending jobs, 0 running jobs and 0 successful_jobs.
03/13/2015 08:34:47 INFO:	 We have found 0 potential job(s) matching 'Thunderbird comm-central win32 l10n nightly' on default. We need to trigger more.
03/13/2015 08:34:47 INFO:	 We want to trigger 'Thunderbird comm-central win32 l10n nightly' on revision 'default' a total of 1 time(s).
03/13/2015 08:34:47 DEBUG:	 Determine if the revision is valid for buildapi.
03/13/2015 08:34:47 DEBUG:	 Determine repository associated to comm-central
03/13/2015 08:34:47 DEBUG:	 About to fetch https://hg.mozilla.org/comm-central/json-pushes?changeset=default&tipsonly=1&full=1
03/13/2015 08:34:47 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/13/2015 08:34:48 DEBUG:	 "GET /comm-central/json-pushes?changeset=default&tipsonly=1&full=1 HTTP/1.1" 200 339
03/13/2015 08:34:48 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/13/2015 08:34:48 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/13/2015 08:34:49 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
03/13/2015 08:34:50 DEBUG:	 Buildername Thunderbird comm-central win32 l10n nightly is valid.
03/13/2015 08:34:50 DEBUG:	 Computing builders' relations from allthethings data.
03/13/2015 08:34:50 DEBUG:	 Buildername Thunderbird comm-central win32 l10n nightly is valid.
03/13/2015 08:34:50 INFO:	 Dry-run: We were going to request 'Thunderbird comm-central win32 l10n nightly' 1 times.
03/13/2015 08:34:50 INFO:	 Dry-run: We were going to post to this url: https://secure.pub.build.mozilla.org/buildapi/self-serve/comm-central/builders/Thunderbird comm-central win32 l10n nightly/default
03/13/2015 08:34:50 INFO:	 Dry-run: with this payload: {'properties': '{"branch": "comm-central", "revision": "default"}'}
03/13/2015 08:34:50 INFO:	 https://treeherder.mozilla.org/#/jobs?repo=comm-central&fromchange=default&tochange=default&filter-searchStr=Thunderbird+comm-central+win32+l10n+nightly
(venv)alice@alice-UX303LN:~/mozilla_ci_tools$

**Comment by armenzg** [comment]
> "Thunderbird comm-central win32 l10n nightly" is considered a build job, thought.
> Should it be considered a test job? It does not belong to any test scheduler in allthethings.json.

"TB WINNT 5.2 comm-aurora nightly" is the upstream builder and "Thunderbird comm-central win32 l10n nightly" is the downstream builder.

**Comment by armenzg** [comment]
L10n is funky.
Even if an L10n builder is downstream, we can simply trigger the builder without needing to specify the files to use or being blocked on an upstream builder to have run on that revision.

For now, let's associated them like any downstream/upstream pairs, however, the day we have a user for L10n we should see if any other changes are needed.

**Comment by armenzg** [comment]
No real user behind this.
