### ISSUE TITLE
All files downloaded or created should be stored inside of a directory

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#125]
As we use the various scripts, we keep on creating lots of .js, .json and .txt files.
If you run the script from within the script directory, you will also create them there.

Instead of creating files under the current working directory, we should generate a unique directory where all these files are put under.

Once we accomplish this we will be able to update the .gitignore file to only ignore such directory and undo the lines for .js, .json and .txt files.

**Comment by jmaher** [comment]
could we be smart and if the file we are downloading exists we can reuse it?  maybe for something like builds4hr.js if it is <15 minutes old we reuse it?

**Comment by armenzg** [comment]
Yes, that is what we currently do.
This issue is about keeping things tidy; not mixing source files with generated artifacts.

We have all sorts of files that start accumulating:
armenzg@armenzg-thinkpad:~/repos/ci_tools$ ls -l *js* *txt
-rw-rw-r-- 1 armenzg armenzg  11183291 Mar 12 12:35 allthethings.json
-rw-rw-r-- 1 armenzg armenzg 269029858 Mar  3 09:57 builds-2015-01-09.js
-rw-rw-r-- 1 armenzg armenzg 265520156 Mar  3 09:57 builds-2015-01-13.js
-rw-rw-r-- 1 armenzg armenzg 217395146 Mar  3 10:17 builds-2015-01-14.js
-rw-rw-r-- 1 armenzg armenzg 256228254 Mar  3 10:18 builds-2015-01-16.js
-rw-rw-r-- 1 armenzg armenzg 236701442 Mar  3 14:59 builds-2015-01-23.js
-rw-rw-r-- 1 armenzg armenzg 131974923 Mar  3 15:24 builds-2015-02-07.js
-rw-rw-r-- 1 armenzg armenzg 251514503 Mar  3 15:24 builds-2015-02-10.js
-rw-rw-r-- 1 armenzg armenzg 261466795 Mar  3 15:23 builds-2015-02-11.js
-rw-rw-r-- 1 armenzg armenzg 132366325 Mar  3 15:23 builds-2015-02-14.js
-rw-rw-r-- 1 armenzg armenzg 194907729 Mar  3 15:22 builds-2015-02-17.js
-rw-rw-r-- 1 armenzg armenzg 211373269 Mar  3 15:22 builds-2015-02-18.js
-rw-rw-r-- 1 armenzg armenzg 195685928 Mar  3 12:31 builds-2015-02-19.js
-rw-rw-r-- 1 armenzg armenzg 200949451 Mar  3 12:02 builds-2015-02-20.js
-rw-rw-r-- 1 armenzg armenzg 228738300 Mar  3 11:19 builds-2015-02-26.js
-rw-rw-r-- 1 armenzg armenzg 227776770 Mar  4 02:54 builds-2015-03-03.js
-rw-rw-r-- 1 armenzg armenzg 230077579 Mar  4 18:22 builds-2015-03-04.js
-rw-rw-r-- 1 armenzg armenzg 252527223 Mar  6 08:57 builds-2015-03-05.js
-rw-rw-r-- 1 armenzg armenzg  36266282 Mar 11 10:25 builds-4hr.js
-rw-rw-r-- 1 armenzg armenzg     19226 Mar  6 11:32 graph.json
-rw-rw-r-- 1 armenzg armenzg   2842375 Mar 12 10:29 log.txt

**Comment by armenzg** [comment]
We can probably create a file store under $HOME/.mozila/mozci

**Comment by adusca** [comment]
Fixed in #148
