### ISSUE TITLE
Give pushlog the ability to navigate through merges

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#127]
If we want to trace an intermittent orange through various repositories we need to also follow through merges.

**Comment by vaibhavmagarwal** [comment]
Is this still a goal? Also, I think mozci is for triggering purposes, I am not sure if this can be realistically achieved in mozci.

**Comment by armenzg** [comment]
Let's close it.
This was meant to chasing intermittent oranges, however, we have proven that in most cases we can't find root issues through backfilling.
