### ISSUE TITLE
Add the ability to inspect the reason of a job failure

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#128]
When chasing intermittent oranges, we want to be able to determine if a test failure is caused by test we're chasing or another one.

We currently can only tell if a job has failed, however, we don't know
which test(s) have failed.

If we want to find intermittent oranges we would need to determine if a job
has failed because the test we care about has actually failed.

A possible way to determine this would be to grab the structured log [1]
uploaded through blobber [2].

**NOTE**: Reftests currently don't generate structured logs. In such case
we would have to fallback to parsing logs. We would have to request this to be
implemented.

**NOTE 2**: In the future, we might be able to query this information through the big
data project.

[1] http://mozbase.readthedocs.org/en/latest/mozlog_structured.html
[2] https://github.com/mozilla/build-blobber

**Comment by vaibhavmagarwal** [comment]
I think we can close this issue too, since we have closed the related issue - https://github.com/armenzg/mozilla_ci_tools/issues/127
