### ISSUE TITLE
Add the ability to monitor jobs

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#131]
We currently trigger jobs and don’t have an standardized method to monitor such
triggered jobs.

**NOTE:** The following would only apply if we don't add Pulse support.

We would need to take this into consideration for Buildbot jobs (without Pulse):

* A job goes from pending to running

  * This would require monitoring builds-pending.js and builds-running.js
  * Unless canceled (we can query buildapi for cancelations)

* A job goes from running to completed

  * At that point it would show up in builds-4hr.js.gz

**Comment by vaibhavmagarwal** [comment]
@armenzg since we now have pulse_actions to monitor jobs, can we close this issue too?

**Comment by armenzg** [comment]
Since we're moving to the TC scheduling instead of BuildAPI we can close this.
