### ISSUE TITLE
When buildapi goes "service unavailable" we should be able to recover

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#136]
03/14/2015 02:06:15 INFO:	 We want to have 30 job(s) of Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3 on revisions [u'003cac9e4e67', u'eb1d40720855', u'9a2b3b8289ee']
03/14/2015 02:06:15 INFO:	 
03/14/2015 02:06:15 INFO:	 === 003cac9e4e67 ===
03/14/2015 02:06:16 INFO:	 We want to have 30 job(s) of Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3 on revision 003cac9e4e67
03/14/2015 02:06:40 INFO:	 We have found 0 potential job(s) matching 'Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3' on 003cac9e4e67. We need to trigger more.
03/14/2015 02:06:40 INFO:	 We want to trigger 'Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3' on revision '003cac9e4e67' a total of 30 time(s).
03/14/2015 02:06:51 INFO:	 There is a _build_ job that has completed successfully.
03/14/2015 02:07:00 INFO:	 We can trigger the downstream job.
03/14/2015 02:07:00 INFO:	 Dry-run: We were going to request 'Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3' 30 times.
03/14/2015 02:07:00 INFO:	 Dry-run: We were going to post to this url: https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/builders/Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3/003cac9e4e67
03/14/2015 02:07:00 INFO:	 Dry-run: with this payload: {'files': '["http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-linux-debug/1425616415/firefox-39.0a1.en-US.linux-i686.tar.bz2", "http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-linux-debug/1425616415/firefox-39.0a1.en-US.linux-i686.tests.zip"]', 'properties': '{"branch": "mozilla-inbound", "revision": "003cac9e4e67"}'}
03/14/2015 02:07:00 INFO:	 
03/14/2015 02:07:00 INFO:	 === eb1d40720855 ===
03/14/2015 02:07:01 INFO:	 We want to have 30 job(s) of Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3 on revision eb1d40720855
03/14/2015 02:07:11 INFO:	 We have found 1 potential job(s) matching 'Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3' on eb1d40720855. We need to trigger more.
03/14/2015 02:07:11 INFO:	 We want to trigger 'Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3' on revision 'eb1d40720855' a total of 29 time(s).
03/14/2015 02:07:22 INFO:	 There is a _build_ job that has completed successfully.
03/14/2015 02:07:29 INFO:	 We can trigger the downstream job.
03/14/2015 02:07:29 INFO:	 Dry-run: We were going to request 'Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3' 29 times.
03/14/2015 02:07:29 INFO:	 Dry-run: We were going to post to this url: https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/builders/Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3/eb1d40720855
03/14/2015 02:07:29 INFO:	 Dry-run: with this payload: {'files': '["http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-linux-debug/1425602358/firefox-39.0a1.en-US.linux-i686.tar.bz2", "http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-linux-debug/1425602358/firefox-39.0a1.en-US.linux-i686.tests.zip"]', 'properties': '{"branch": "mozilla-inbound", "revision": "eb1d40720855"}'}
03/14/2015 02:07:29 INFO:	 
03/14/2015 02:07:29 INFO:	 === 9a2b3b8289ee ===
03/14/2015 02:07:30 INFO:	 We want to have 30 job(s) of Ubuntu VM 12.04 mozilla-inbound debug test mochitest-3 on revision 9a2b3b8289ee
03/14/2015 02:08:25 ERROR:	 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Service Unavailable</title>
<style type="text/css">
body, p, h1 {
  font-family: Verdana, Arial, Helvetica, sans-serif;
}
h2 {
  font-family: Arial, Helvetica, sans-serif;
  color: #b10b29;
}
</style>
</head>
<body>
<h2>Service Unavailable</h2>
<p>The service is temporarily unavailable. Please try again later.</p>
</body>
</html>
Traceback (most recent call last):
  File "trigger.py", line 170, in <module>
    dry_run=options.dry_run
  File "/home/vaibhav/mozilla_ci_tools/mozci/mozci.py", line 360, in trigger_range
    jobs = query_jobs(repo_name, rev)
  File "/home/vaibhav/mozilla_ci_tools/mozci/mozci.py", line 183, in query_jobs
    return buildapi.query_jobs_schedule(repo_name, revision)
  File "/home/vaibhav/mozilla_ci_tools/mozci/sources/buildapi.py", line 155, in query_jobs_schedule
    assert req.status_code in [200], req.content
AssertionError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<title>Service Unavailable</title>
<style type="text/css">
body, p, h1 {
  font-family: Verdana, Arial, Helvetica, sans-serif;
}
h2 {
  font-family: Arial, Helvetica, sans-serif;
  color: #b10b29;
}
</style>
</head>
<body>
<h2>Service Unavailable</h2>
<p>The service is temporarily unavailable. Please try again later.</p>
</body>
</html>

**Comment by armenzg** [comment]
It is a buildapi issue.
https://mozilla-ci-tools.readthedocs.org/en/latest/faq.html#what-are-the-concerns-of-trigger-a-large-number-of-jobs-in-a-short-period-of-time

Unfortunately, releng worries that exposing the issues could reveal some passwords or secrets on the host.

Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1087336.

I *could* find some of these issues if you let me know and I would in the logs, however, I only have partial access.

**Comment by armenzg** [comment]
In that bug dustin tells me that we won't have a way to figure out why we are going bad.
We should retry few times by adding some randomize sleep times in between.
We should consider adding "redo" (python package) to help us add rety logic.

**Comment by armenzg** [comment]
@jmaher says to have some code to handle this in his scripts.

**Comment by armenzg** [comment]
@vaibhavmagarwal we now return an empty list instead of dumping the contents of the response.
What would you like to do in here? Close it?
raise a BuildApiError and let it be handle by the calling function?

This:
` assert req.status_code in [200], req.content`

versus this:
`   if req.status_code not in [200]:`
`        return []`

https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L184

**Comment by vaibhavmagarwal** [comment]
Yeah, I am fine with closing this as of now.
