### ISSUE TITLE
NoneType found while parsing build-<date>.js

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#138]
python trigger.py --rev 3ec78ec97624 --back-revisions 30 --times 30 --skip 15 --buildername "Windows 7 32-bit mozilla-inbound opt test mochitest-3" --debug --dry-run
03/15/2015 05:53:13 INFO:	 Setting DEBUG level
03/15/2015 05:53:13 DEBUG:	 Loading /home/jmaher/mozilla/mozilla_ci_tools/scripts/repositories.txt
03/15/2015 05:53:13 DEBUG:	 Determine repository associated to mozilla-inbound
03/15/2015 05:53:13 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=3ec78ec97624&tipsonly=1
03/15/2015 05:53:13 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/15/2015 05:53:13 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=3ec78ec97624&tipsonly=1 HTTP/1.1" 200 137
03/15/2015 05:53:13 DEBUG:	 Push info: {u'date': 1425736151, u'changesets': [u'3ec78ec97624dff4b1ed5d68e57baae9c0a9697f'], u'user': u'kaie@kuix.de', 'pushid': u'56534'}
03/15/2015 05:53:13 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?startID=56503&endID=56534&version=2&tipsonly=1
03/15/2015 05:53:13 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/15/2015 05:53:14 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?startID=56503&endID=56534&version=2&tipsonly=1 HTTP/1.1" 200 1395
03/15/2015 05:53:14 INFO:	 We want to have 30 job(s) of Windows 7 32-bit mozilla-inbound opt test mochitest-3 on revisions [u'3ec78ec97624', u'dc86a4e16519', u'4139522bf814']
03/15/2015 05:53:14 INFO:	 
03/15/2015 05:53:14 INFO:	 === 3ec78ec97624 ===
03/15/2015 05:53:14 DEBUG:	 Determine if the revision is valid for buildapi.
03/15/2015 05:53:14 DEBUG:	 Determine repository associated to mozilla-inbound
03/15/2015 05:53:14 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=3ec78ec97624&tipsonly=1&full=1
03/15/2015 05:53:14 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/15/2015 05:53:15 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=3ec78ec97624&tipsonly=1&full=1 HTTP/1.1" 200 509
03/15/2015 05:53:15 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/15/2015 05:53:15 INFO:	 We want to have 30 job(s) of Windows 7 32-bit mozilla-inbound opt test mochitest-3 on revision 3ec78ec97624
03/15/2015 05:53:15 DEBUG:	 Determine if the revision is valid for buildapi.
03/15/2015 05:53:15 DEBUG:	 Determine repository associated to mozilla-inbound
03/15/2015 05:53:15 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=3ec78ec97624&tipsonly=1&full=1
03/15/2015 05:53:15 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/15/2015 05:53:15 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=3ec78ec97624&tipsonly=1&full=1 HTTP/1.1" 200 509
03/15/2015 05:53:15 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/15/2015 05:53:15 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/3ec78ec97624?format=json
03/15/2015 05:53:15 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/15/2015 05:53:16 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/3ec78ec97624?format=json HTTP/1.1" 200 28235
03/15/2015 05:53:16 DEBUG:	 Find jobs matching 'Windows 7 32-bit mozilla-inbound opt test mochitest-3'
03/15/2015 05:53:16 DEBUG:	 We have found 39 job(s) of 'Windows 7 32-bit mozilla-inbound opt test mochitest-3'.
03/15/2015 05:53:16 DEBUG:	 Job identified with complete_at value: 1426370739 run on 2015-03-14 UTC.
03/15/2015 05:53:16 DEBUG:	 The job completed at Sat, 14 Mar 2015 22:05:39 +0000 (UTC) (11 hours ago).
03/15/2015 05:53:16 INFO:	 Starting new HTTP connection (1): builddata.pub.build.mozilla.org
03/15/2015 05:53:16 DEBUG:	 "GET /builddata/buildjson/builds-2015-03-14.js.gz HTTP/1.1" 200 11627798
03/15/2015 05:53:16 DEBUG:	 About to load builds-2015-03-14.js.
03/15/2015 05:53:18 DEBUG:	 We are going to look for 64445176 in builds-2015-03-14.js.
03/15/2015 05:53:18 ERROR:	 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "trigger.py", line 170, in <module>
    dry_run=options.dry_run
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 362, in trigger_range
    successful_jobs, pending_jobs, running_jobs = _status_summary(matching_jobs)[0:3]
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 46, in _status_summary
    status = buildapi.query_job_status(job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildapi.py", line 129, in query_job_status
    if status_data["properties"]["revision"][0:12] != req["revision"][0:12]:
TypeError: 'NoneType' object has no attribute '__getitem__'
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$ 

I wonder if our tree closure window messed this up in some way.

**Comment by jmaher** [comment]
I deleted all my .js files and did this again, same error, just on a different file.

**Comment by armenzg** [comment]
From what you explain, this can appear on any file that is not downloaded correctly (issue #135)
At worst, it can be related to issue #104 which is unrelated yet I have to fix.

I will hope to have a fix in #135 in the next 2 days and revisit this.

**Comment by armenzg** [comment]
@jmaher I noticed a different bug, it seems that for --times we only count jobs that have turned green.
Should we change the logic? Should we add a way to prevent triggering a lot of jobs because we have not reached the quota of green jobs? (for our current usages of mozci we're fine but for runs with monitoring it might become an issue)

**Comment by vaibhavmagarwal** [comment]
@armenzg I think it should count the green, orange and red jobs - since they were "triggered" and they failed (intermittent, actual bustage) probably because of some error in the developers patch.

**Comment by jmaher** [comment]
Agreed.  We can ignore coalesced jobs for now.

Joel

**Comment by armenzg** [comment]
I wasn't talking about coalesced jobs.

Let's say we want 15 jobs on a push.
We run the script once.
15 jobs appear: some green, some non-green
We run the script again (for the giggles)
We will schedule as many non-green jobs there are on that push.

We can leave it as-is but want to make sure that it is clearly understood what the current behaviour is.

**Comment by jmaher** [comment]
and I think that is wrong as we should only count total jobs run regardless
of the status.  Maybe a cli option to have --ignore-failures or something
like that- it gets complicated quickly though.

**Comment by armenzg** [comment]
Filed issue #145. Please let me know if I got it right.

**Comment by jmaher** [comment]
it looks right to me.

**Comment by armenzg** [comment]
Could you please pull and try again?

You should start seeing messages like this for buildjson files that are older:
> "The local file was last modified in %s. We need to delete the file and fetch it again." % last_mod_date

https://github.com/armenzg/mozilla_ci_tools/commit/c01fcb8f0c301db33d84a5752f26b2c09007182e#diff-7d9f2fa2b0e39837fed14dcef78e6b17R34

**Comment by armenzg** [comment]
Closing until I hear otherwise.
