### ISSUE TITLE
test_platforms.py can start failing when the list of builders changes

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#144]
Every time the list of buildbot builders change, our test_platform.py test is likely to start failing.
We might need to change the design of this test completely. I don't know what the right approach should be.

__________________________________________________ test_get_associated_platform_name[Android 2.3 mozilla-release build-android] __________________________________________________

builder = 'Android 2.3 mozilla-release build', expected = 'android'

    @pytest.mark.parametrize("builder, expected", get_platform_test_cases)
    def test_get_associated_platform_name(builder, expected):
        """Test get_associated_platform_name() with test cases from get_platform_test_cases."""
>       obtained = mozci.platforms.get_associated_platform_name(builder)

test/test_platforms.py:117: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

buildername = 'Android 2.3 mozilla-release build'

    def get_associated_platform_name(buildername):
        """Given a buildername, find the platform in which it is ran."""
>       props = fetch_allthethings_data()['builders'][buildername]['properties']
E       KeyError: 'Android 2.3 mozilla-release build'

mozci/platforms.py:135: KeyError

**Comment by adusca** [comment]
Originally I was trying to test as many builders as possible to validate the new heuristic for determine_upstream_builder(). I believe now that the new heuristic has proved itself we should move to mocking based tests. I'll be working on that. If we ever decide to change heuristics again we may come back to comprehensive testing.

**Comment by armenzg** [comment]
Thanks Alice. It makes sense to me.

I have disabled all b2g jobs since a lot of them have moved to TaskCluster. Others will stick around for a while, however, I did a mass clean up rather than have to research lots and have to maintain the list:
https://github.com/armenzg/mozilla_ci_tools/commit/54ec1aac4d7e04e001a8368ee0fa85061c859fd8
