### ISSUE TITLE
Add the ability to trigger b2g jobs

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#147]
We have lost that recently when we move the builds to TaskCluster.

**Comment by armenzg** [comment]
Related https://bugzilla.mozilla.org/show_bug.cgi?id=1174236

**Comment by vaibhavmagarwal** [comment]
This looks like a duplicate of https://github.com/armenzg/mozilla_ci_tools/issues/132 . Should we close this and track the issue there?

**Comment by armenzg** [comment]
Let's dupe it against it.
