### ISSUE TITLE
Do not allow any corrupted json data

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#154]
It seems that jmaher is hitting this.
His builds4hr file: http://people.mozilla.org/~jmaher/builds-4hr.js

jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$ python alltalos.py --repo-name try --rev 112e534ec58a --times 1
04/06/2015 10:27:15 INFO:	 We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos chromez' on revision '112e534ec58a' a total of 1 time(s).
04/06/2015 10:27:22 INFO:	 There is a _build_ job that has completed successfully.
04/06/2015 10:27:22 INFO:	 We have the necessarily files to trigger the downstream job.
04/06/2015 10:27:23 INFO:	 We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos dromaeojs' on revision '112e534ec58a' a total of 1 time(s).
04/06/2015 10:27:33 INFO:	 There is a _build_ job that has completed successfully.
04/06/2015 10:27:33 INFO:	 We have the necessarily files to trigger the downstream job.
04/06/2015 10:27:34 INFO:	 We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos g1' on revision '112e534ec58a' a total of 1 time(s).
04/06/2015 10:27:41 INFO:	 There is a _build_ job that has completed successfully.
04/06/2015 10:27:41 INFO:	 We have the necessarily files to trigger the downstream job.
04/06/2015 10:27:42 INFO:	 We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos other_nol64' on revision '112e534ec58a' a total of 1 time(s).
04/06/2015 10:27:49 INFO:	 There is a _build_ job that has completed successfully.
04/06/2015 10:27:49 INFO:	 We have the necessarily files to trigger the downstream job.
04/06/2015 10:27:50 INFO:	 We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos svgr' on revision '112e534ec58a' a total of 1 time(s).
04/06/2015 10:28:05 INFO:	 There is a _build_ job that has completed successfully.
04/06/2015 10:28:05 INFO:	 We have the necessarily files to trigger the downstream job.
04/06/2015 10:28:06 INFO:	 We want to trigger 'Rev5 MacOSX Yosemite 10.10 try talos tp5o' on revision '112e534ec58a' a total of 1 time(s).
Traceback (most recent call last):
  File "alltalos.py", line 86, in <module>
    main()
  File "alltalos.py", line 83, in main
    dry_run=options.dry_run)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 335, in trigger_job
    buildername,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 126, in _determine_trigger_objective
    files = _find_files(job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 180, in _find_files
    job_status = _status_info(job_schedule_info)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 173, in _status_info
    return buildjson.query_job_data(complete_at, request_id)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 138, in query_job_data
    job = _find_job(request_id, _fetch_file(BUILDS_4HR_FILE), BUILDS_4HR_FILE)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 35, in _fetch_file
    builds = json.load(open(path_to_file(filename)))["builds"]
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 220464 column 13 (char 10258100)
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$ ^C
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$

**Comment by vaibhavmagarwal** [comment]
I too have encountered this sometimes, but I found that the trees were closed when I faced them...

**Comment by armenzg** [comment]
I have found that the builds-4hr was incomplete (see how it just stops):
    "3240": "panda-0552",
    "3241": "panda-0577",
    "3242": "panda-0

**Comment by armenzg** [comment]
@jmaher 

We should add better support to detect that the file has not been downloaded propertly (the request did not complete succesfully) and retry, however, if we find that it is the releng system that is temporarily giving a bad file we should retry a bit later.

The other option is to fallback to treeherder's API, however, for running jobs, it also feeds from builds-4hr. Warning: treeherder can always have data sligthly out-of-date.

**Comment by armenzg** [comment]
I will be landing some code in the next hour.

1) It prevents writing to disk any files that are corrupted [1]
* It will now exit. We can change this behaviour
2) If the file on disk is already corrupted it will rename it to "filename.corrupted" for inspection [2]
* The next run will not contain the corrupted file in the file directory

[1]
armenzg@armenzg-thinkpad:~/repos/ci_tools$ python scripts/misc/download_file.py http://people.mozilla.org/~jmaher/builds-4hr.js
04/06/2015 03:45:55 DEBUG:	 We have not been able to find on disk /home/armenzg/.mozilla/mozci/builds-4hr.js.
04/06/2015 03:45:55 INFO:	 Starting new HTTP connection (1): people.mozilla.org
04/06/2015 03:45:55 DEBUG:	 "GET /~jmaher/builds-4hr.js HTTP/1.1" 200 10258108
04/06/2015 03:45:55 DEBUG:	 About to fetch /home/armenzg/.mozilla/mozci/builds-4hr.js from http://people.mozilla.org/~jmaher/builds-4hr.js
04/06/2015 03:46:05 ERROR:	 The obtained json from http://people.mozilla.org/~jmaher/builds-4hr.js came corrupted. We're not writing to disk.

[2]
armenzg@armenzg-thinkpad:~/repos/ci_tools$ python scripts/misc/download_file.py http://people.mozilla.org/~jmaher/builds-4hr.js
04/06/2015 03:48:00 INFO:	 Starting new HTTP connection (1): people.mozilla.org
04/06/2015 03:48:00 DEBUG:	 "GET /~jmaher/builds-4hr.js HTTP/1.1" 304 0
04/06/2015 03:48:00 DEBUG:	 /home/armenzg/.mozilla/mozci/builds-4hr.js is on disk and was last modified on Mon, 06 Apr 2015 19:47:59 GMT
04/06/2015 03:48:00 DEBUG:	 About to load /home/armenzg/.mozilla/mozci/builds-4hr.js.
04/06/2015 03:48:01 ERROR:	 Unterminated string starting at: line 220464 column 13 (char 10258100)
Traceback (most recent call last):
  File "scripts/misc/download_file.py", line 27, in <module>
    builds = json.load(open(filepath))["builds"]
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 220464 column 13 (char 10258100)
04/06/2015 03:48:01 ERROR:	 The file on-disk does not have valid data
04/06/2015 03:48:01 INFO:	 We have moved /home/armenzg/.mozilla/mozci/builds-4hr.js to builds-4hr.js.corrupted for inspection.

**Comment by armenzg** [comment]
@jmaher This issue has been fixed. Please let us know what is your preferred behaviour instead of exiting.

https://github.com/armenzg/mozilla_ci_tools/commit/1a29caa20f4297e0dcbe5e3b48db4231b4f8c30c

**Comment by jmaher** [comment]
A good error message and a failure is fine- I guess it would be nice to continue on and try to work and log which jobs fail to launch, etc.

so ideally we could run this again with a script to parse the jobs that didn't run

**Comment by armenzg** [comment]
With the latest changes we give meaningful messages.
Re-running the script will continue without any issues (unless the releng systems are the ones providing a corrupted file).
Closing for now since at least we can recuperate for most cases.
