### ISSUE TITLE
Be more verbose about credential storage

### ISSUE THREAD

**Issue by Callek** [armenzg/mozilla_ci_tools#155]
When saving credentials should output where it was saved to, since the script prompts for them on first use.

Should also output where it was read from when accessing on future script runs.

This will help for cases where credentials may be valid but wrong (and I have another set), or for cases where I need to clear them (say I'm on a remote machine).

**Comment by adusca** [comment]
After PR #162 we output where the credentials will be stored when we ask for them. We also output where it was read from when running in --debug mode.
