### ISSUE TITLE
Do not trigger build because it turned orange

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#157]
This is an example of this scenario:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=4dff56e21e1e

The Windows build was orange, however, the builds and test.zip had been uploaded without any issues.
We could re-use this build without needing to trigger another one.

@jmaher wfu?

**Comment by jmaher** [comment]
I would be happy to use a build/tests.zip if it already exists.  This is
corner case land, but good practice.

**Comment by adusca** [comment]
#220
