### ISSUE TITLE
Prompt for credentials as soon as possible

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#158]
I think we currently prompt once we are about to make a post request. [1]

We should fix the trigger.py and alltalos.py to fix this.
We should also try to tackle not storing the password in clear text.

[1] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L59

**Comment by vaibhavmagarwal** [comment]
This issue can be closed, as we prompt for credentials at start: https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/mozci.py#L391 and do not store passwords in clear text.
