### ISSUE TITLE
unable to trigger job due to not finding id in builds-xxxxxx.js

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#167]
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$ python alltalos.py --repo-name mozilla-aurora --times 10 --rev 61d78164c214 --pgo --debug
04/27/2015 10:40:00 INFO:	 Setting DEBUG level
04/27/2015 10:40:00 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
04/27/2015 10:40:01 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
04/27/2015 10:40:01 DEBUG:	 Loading /home/jmaher/.mozilla/mozci/repositories.txt
04/27/2015 10:40:01 INFO:	 We want to trigger 'Ubuntu HW 12.04 mozilla-aurora pgo talos chromez' on revision '61d78164c214' a total of 10 time(s).
04/27/2015 10:40:01 DEBUG:	 Determine if the revision is valid in buildapi.
04/27/2015 10:40:01 DEBUG:	 Loading LDAP credentials from /home/jmaher/.mozilla/credentials.cfg
04/27/2015 10:40:01 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
04/27/2015 10:40:02 DEBUG:	 "GET /buildapi/self-serve/mozilla-aurora/rev/61d78164c214?format=json HTTP/1.1" 200 48562
04/27/2015 10:40:02 DEBUG:	 Buildername Ubuntu HW 12.04 mozilla-aurora pgo talos chromez is valid.
04/27/2015 10:40:02 DEBUG:	 Computing builders' relations from allthethings data.
04/27/2015 10:40:02 DEBUG:	 Buildername Linux mozilla-aurora build is valid.
04/27/2015 10:40:02 DEBUG:	 Determine if the revision is valid in buildapi.
04/27/2015 10:40:02 DEBUG:	 Loading LDAP credentials from /home/jmaher/.mozilla/credentials.cfg
04/27/2015 10:40:02 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
04/27/2015 10:40:03 DEBUG:	 "GET /buildapi/self-serve/mozilla-aurora/rev/61d78164c214?format=json HTTP/1.1" 200 48710
04/27/2015 10:40:03 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-aurora/rev/61d78164c214?format=json
04/27/2015 10:40:03 DEBUG:	 Loading LDAP credentials from /home/jmaher/.mozilla/credentials.cfg
04/27/2015 10:40:03 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
04/27/2015 10:40:04 DEBUG:	 "GET /buildapi/self-serve/mozilla-aurora/rev/61d78164c214?format=json HTTP/1.1" 200 48710
04/27/2015 10:40:05 DEBUG:	 Find jobs matching 'Linux mozilla-aurora build'
04/27/2015 10:40:05 DEBUG:	 We have found 1 job(s) of 'Linux mozilla-aurora build'.
04/27/2015 10:40:05 DEBUG:	 List of matching jobs:
04/27/2015 10:40:05 DEBUG:	 Job identified with complete_at value: 1429967139 run on 2015-04-25 UTC.
04/27/2015 10:40:05 DEBUG:	 The job completed at Sat, 25 Apr 2015 13:05:39 +0000 (UTC) (49 hours ago).
04/27/2015 10:40:05 INFO:	 Starting new HTTP connection (1): builddata.pub.build.mozilla.org
04/27/2015 10:40:05 DEBUG:	 "GET /builddata/buildjson/builds-2015-04-25.js.gz HTTP/1.1" 304 0
04/27/2015 10:40:05 DEBUG:	 Mon, 27 Apr 2015 14:37:51 GMT is on disk and it is current.
04/27/2015 10:40:05 DEBUG:	 About to load /home/jmaher/.mozilla/mozci/builds-2015-04-25.js.
04/27/2015 10:40:06 DEBUG:	 We are going to look for 68131370 in builds-2015-04-25.js.
Traceback (most recent call last):
  File "alltalos.py", line 99, in <module>
    main()
  File "alltalos.py", line 96, in main
    dry_run=options.dry_run)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 335, in trigger_job
    buildername,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 120, in _determine_trigger_objective
    status = buildapi.query_job_status(job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildapi.py", line 143, in query_job_status
    req["request_id"])
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 166, in query_job_data
    "inspection. Thanks!" % (filename, request_id)
Exception: We have not found the job. If you see this problem please grep in builds-2015-04-25.js for 68131370 and run again with --debug and --dry-run. If you report this issue please upload the mentioned file somewhere for inspection. Thanks!
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$

**Comment by armenzg** [comment]
Could you please upload that file for me to look into?
Thanks!

**Comment by jmaher** [comment]
uploaded it here:
http://people.mozilla.org/~jmaher/builds-2015-04-25.js

**Comment by armenzg** [comment]
I get a 403.

On 15-04-27 11:23 AM, Joel Maher wrote:
> uploaded it here:
> http://people.mozilla.org/~jmaher/builds-2015-04-25.js
>
>
> On Mon, Apr 27, 2015 at 10:56 AM, Armen Zambrano 
> <notifications@github.com>
> wrote:
>
> > Could you please upload that file for me to look into?
> > Thanks!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/armenzg/mozilla_ci_tools/issues/167#issuecomment-96685903>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/armenzg/mozilla_ci_tools/issues/167#issuecomment-96705650>.
>

-- 
Zambrano Gasparnian, Armen
Automation & Tools Engineer
http://armenzg.blogspot.ca

**Comment by jmaher** [comment]
fix it with chmod :(

**Comment by armenzg** [comment]
Something happened on the buildbot world.
TH shows the job as still running [1]
self-serve believes it is completed [2] (search for "Linux mozilla-aurora build")
If you open the job status [3], you will see it as completed.
If you open the x86-64 job [4], you will see that the data of both the same structure (no missing keys or values).
We even see talos jobs that were triggered by it.
I can even see the job completed on buildbot [5]

Somehow, the data did not make it into buildjson file and that is why mozci and TH fail.
I will see how to best recover and file a releng bug.

[1] https://treeherder.mozilla.org/#/jobs?repo=mozilla-aurora&revision=61d78164c214&filter-searchStr=Linux%20mozilla-aurora%20build
[2] https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-aurora/rev/61d78164c214
[3] https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-aurora/build/69366760
[4] https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-aurora/build/69366768
[5] http://buildbot-master71.bb.releng.use1.mozilla.com:8001/builders/Linux%20mozilla-aurora%20build/builds/150

**Comment by armenzg** [comment]
This can be reproduced with this:
python scripts/misc/find_status_for_jobs.py --buildername "Linux mozilla-aurora build" --revision 61d78164c214 --debug

04/28/2015 11:40:26 DEBUG:	 Find jobs matching 'Linux mozilla-aurora build'
04/28/2015 11:40:26 DEBUG:	 We have found 1 job(s) of 'Linux mozilla-aurora build'.
04/28/2015 11:40:26 DEBUG:	 Job identified with complete_at value: 1429967139 run on 2015-04-25 UTC.
04/28/2015 11:40:26 DEBUG:	 The job completed at Sat, 25 Apr 2015 13:05:39 +0000 (UTC) (74 hours ago).
04/28/2015 11:40:27 DEBUG:	 Tue, 28 Apr 2015 14:15:45 GMT is on disk and it is current.
04/28/2015 11:40:27 DEBUG:	 About to load /home/armenzg/.mozilla/mozci/builds-2015-04-25.js.
04/28/2015 11:40:28 DEBUG:	 We are going to look for 68131370 in builds-2015-04-25.js.
Traceback (most recent call last):
  File "scripts/misc/find_status_for_jobs.py", line 50, in <module>
    status = query_job_status(schedule_info)
  File "/home/armenzg/repos/ci_tools/mozci/sources/buildapi.py", line 143, in query_job_status
    req["request_id"])
  File "/home/armenzg/repos/ci_tools/mozci/sources/buildjson.py", line 166, in query_job_data
    "inspection. Thanks!" % (filename, request_id)
Exception: We have not found the job. If you see this problem please grep in builds-2015-04-25.js for 68131370 and run again with --debug and --dry-run. If you report this issue please upload the mentioned file somewhere for inspection. Thanks!

**Comment by armenzg** [comment]
Buildjson data does not allow us to determine the status of the job.
Since the bug [1] is not going to be fixed we will work around it by pretending the the files are not available on FTP and trigger a new build.
It is a bit costly, however, at least we work around it in a clean manner.

https://github.com/armenzg/mozilla_ci_tools/commit/c41816e54489c289ddb6eb803c26864a73bc078b

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1159279
