### ISSUE TITLE
When triggering on mozilla-aurora/mozilla-beta we have pgo builds, but not pgo branded builders

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#17]
mozilla-aurora/mozilla-beta have pgo runs, but the platform buildername returns as:
Linux x86-64 mozilla-beta pgo-build

when it should be:
Linux x86-64 mozilla-beta build

this appears to be specific to the beta/aurora branches- maybe we can either put a hack in place or restrict the use of this tool to not work on those branches.

I found this while testing talos retriggers on those branches.

**Comment by armenzg** [comment]
On the bisection branch:
>>> from mozci.platforms import associated_build_job
>>> associated_build_job("Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez", "mozilla-beta")
u'Linux x86-64 mozilla-beta build'

On the master branch:
>>> associated_build_job("Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez", "mozilla-beta")
'Linux x86-64 mozilla-beta pgo-build'

**Comment by jmaher** [comment]
hmm bisection branch has some troubles:
python trigger.py  --dry-run --debug --repo-name try --rev 36610eaaf033 -b "Rev5 MacOSX Mountain Lion 10.8 try talos svgr"
Traceback (most recent call last):
  File "trigger.py", line 8, in <module>
    from mozci.mozci import trigger_job, query_jobs_schedule_url
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 13, in <module>
    import platforms
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/platforms.py", line 37, in <module>
    buildername_to_trigger[builder] = values['triggered_by'][0]
KeyError: 'triggered_by'
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$ git branch
* bisection
  master
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$

**Comment by jmaher** [comment]
ok, this is working better on the bisection branch- other issues, but this can be closed
