### ISSUE TITLE
Write way to read status from treeherder instead of buildjson for status of jobs

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#178]
We currently use buildjson due to accuracy, however, we should start the support for treeherder and have a way to configure what to use.

We should report status issues of TH so they get addressed.

**Comment by vaibhavmagarwal** [comment]
We use buildjson.py to fetch and search request_ids: https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildjson.py

What are the api(s) in treeherder to get the statuses of jobs in TH?

**Comment by vaibhavmagarwal** [comment]
I found the api docs here: http://treeherder-dev.allizom.org/docs/
But it is still unclear which api(s) we will need since it will depend on what functionality we are targetting initially.

**Comment by armenzg** [comment]
I had trouble understanding that API. I think it is best to ask emorley, camd or mdoglio for specifics.

The way that I do it for buildapi/buildjson is:
1) Give me all jobs for this tree/revision from *buildapi*

After that I filter down to what I specifically need and then look for specific info about specific jobs through _buildjson_.

Does this help?

**Comment by vaibhavmagarwal** [comment]
Let me get this clear in my head. As far as I understand, we can just query treeherder to know which jobs have finished vs still running. To trigger the jobs we will still need buildapi. I think that the re-trigger button in treeherder ui uses buildapi in its back end but I am not sure. @armenzg am i correct? If yes, then we need to find the api in treeherder to query the status of jobs (running vs finished vs failed) like in your original comment.

**Comment by armenzg** [comment]
You got it all right.
To trigger jobs we won't need buildjson since all we do is hit the buildapi rest API (_make_request())

I believe TH has an API but tbh I can't figure out from looking at the docs/api page you pasted.

**Comment by armenzg** [comment]
Will tells me that there is a treeherder client which we could improve and add as a dependency.
https://treeherder-service.readthedocs.org/en/latest/submitting_data.html#treeherder-python-client-library
https://bugzilla.mozilla.org/show_bug.cgi?id=1163674

I think the client is currently only desgined to submit data but Will would also like to see having the ability to query information from TH.

**Comment by vaibhavmagarwal** [comment]
Had a chat with :camd who helped me figure out how to get the status of jobs from treeherder api. Assuming we have the revision and buildername, we have two steps:
1) From the revision, get the revision id. Eg:
https://treeherder.mozilla.org/api/project/mozilla-inbound/resultset/?count=10&full=true&revision=5943d32f3515
revision id is "id": 14746

2) From the revision id, get the list of all jobs with buildernames in it:
Eg:
https://treeherder.mozilla.org/api/project/mozilla-inbound/jobs/?count=2000&result_set_id=14746
The "ref_data_name" parameter is the buildername of the job, after which we can get the corresponding "result" which is the status.

**Comment by vaibhavmagarwal** [comment]
Also filed a bug to have this functionality in one api call in https://bugzilla.mozilla.org/show_bug.cgi?id=1165401

**Comment by vaibhavmagarwal** [comment]
There are various statuses for jobs as stated in: https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L32

On chatting with :camd, I got to know how to find these out in TH api, for my future reference I am pasting the mapping here: https://pastebin.mozilla.org/8833952

**Comment by vaibhavmagarwal** [comment]
This is my first stab at making query_job_status function: https://pastebin.mozilla.org/8833967
@armenzg if you could give a general feedback on this, it would be good to know how I should proceed.

**Comment by armenzg** [comment]
This looks in the right direction and it shows you got the jist of it. Excellent!

Would you mind checking with @wlach to see if any of this functionality make sense to add it to the TH client? We could then add it as a dependency to mozci.

I'm also thinking that we would want to add some object orientation to mozci (I'm planning to do this for other parts of the repo - specifically with TaskCluster support).
I would like to consider something like a StatusManager base class and extending it with BuildapiStatusManager and a TreeherderStatusManager.
I would also like to see a status.py module.
By doing this, we can make the functionality be pretty much drop in and replace.
It is a decent re-factoring but it would pay off in the long term.

This might also be an opportunity to define a basic Job class.

Is this latter part something you would like to tackle now as part of this?
I see it being more difficult to review and test the code without it.

Is get_revision_id() to determine the "push id" of the revision?
I think you call it "revision id" instead of "push id". I grabbed the terminology from the pushlog documentation. [1]
This is similar functionality as the one obtained through the pushlog module [2]

Could you make count an optional parameter set to 2000?
> url = "%s/%s/jobs/?count=2000&result_set_id=%s" % (HOST_ROOT, repo_name, revision_id)

[1] http://mozilla-version-control-tools.readthedocs.org/en/latest/hgmo/pushlog.html
[2] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/pushlog.py

**Comment by armenzg** [comment]
Why 2000?

**Comment by vaibhavmagarwal** [comment]
Armen,

I will chat with @wlach to see if this is useful in TH client. Regarding bringing OOP to mozci, I think it is a good move, I too was saw that we are unnecessary duplicating certain things here.
 Regarding get_revision_id(), I am not sure that the "revision id" in get_revision_id() function is the same as "push id". For example,
Lets take https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=9841c5d229b8
The corresposing revision is: https://hg.mozilla.org/integration/mozilla-inbound/rev/9841c5d229b8
The changeset number (or "push id") is 244621 : https://hg.mozilla.org/integration/mozilla-inbound/rev/244621

But if you look in TH api: https://treeherder.mozilla.org/api/project/mozilla-inbound/resultset/?count=10&full=true&revision=9841c5d229b8 , you will see the "revision id" is 14925... so my guess is here TH has a separate id naming for revision.

Lastly, your query regarding 2000 in:
    url = "%s/%s/jobs/?count=2000&result_set_id=%s" % (HOST_ROOT, repo_name, revision_id)

Here 'count' parameter decides how many jobs are displayed for a given revision. Now I wanted all the jobs to be displayed, and I don't know beforehand the total number of jobs. So, I have given the count as 2000, because normally the number of jobs for a given revision is <1000, so 2000 looks like a safe number to get *all* the jobs for a revision. 

Let me know your thoughts and suggestions.

**Comment by armenzg** [comment]
Thanks for clarifying that! I'm glad I asked :P If we could add that the ID is a unique identifier for TH as a comment it would be great.

What happens if you do  not specify count? Does it fail?
Could it be a bug on TH?
Either way works for me. You seem to choose a safe number in my opinion.

**Comment by vaibhavmagarwal** [comment]
If I do not specify "count" parameter, it defaults to 10 and thus does not solve our purpose of getting all jobs for a revision. So I have chosen 2000

**Comment by armenzg** [comment]
I was thinking about this and the first place where we would gain a lot of value is for when we fetch the builds-4hr files.
This would be a noticeable improvements for running alltalos.py against revisions that had been pushed in the last few hours.

**Comment by vaibhavmagarwal** [comment]
The relevant changes for th-client is already merged. After some refactoring, we should be able to include the functionality to query TH for job status. I am thinking on the possible way of configuration for this. One way to do the configuration can be to have a --configure "Treeherder" flag in the scripts to get the status from Treeherder. Another way can be to have a file and specify something like "use:Treeherder" or "use:Buildapi". Thoughts? Any other way we can do this configuration?

**Comment by armenzg** [comment]
Let's use the flag and default to buildapi for now. What do you think of --status-provider?
Eventually we will transition from one to the other.
Sorry it took so long! Too many meetings!

**Comment by armenzg** [comment]
Here's the bug that prevents us from having accurate information about pending jobs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1059909

This would probably not be an issue on TaskCluster.
Perhaps we should only use Treeherder status for TaskCluster tasks.

**Comment by vaibhavmagarwal** [comment]
Fixed in https://github.com/armenzg/mozilla_ci_tools/pull/257
