### ISSUE TITLE
empty status while triggering beta build

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#18]
02/18/2015 04:33:06 DEBUG:	 We want to trigger 'Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez' on revision '948a2c2e31d4' a total of 2 times.
02/18/2015 04:33:06 DEBUG:	 Buildername Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez is valid.
02/18/2015 04:33:06 DEBUG:	 The build job that triggers Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez is Linux x86-64 mozilla-beta pgo-build
02/18/2015 04:33:07 DEBUG:	 Buildername Linux x86-64 mozilla-beta build is valid.
02/18/2015 04:33:07 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-beta/rev/948a2c2e31d4?format=json
02/18/2015 04:33:07 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
02/18/2015 04:33:07 DEBUG:	 "GET /buildapi/self-serve/mozilla-beta/rev/948a2c2e31d4?format=json HTTP/1.1" 200 19063
02/18/2015 04:33:07 DEBUG:	 Find jobs matching 'Linux x86-64 mozilla-beta build'
02/18/2015 04:33:07 DEBUG:	 We have matched 1 jobs.
02/18/2015 04:33:07 DEBUG:	 List of matching jobs:
02/18/2015 04:33:07 DEBUG:	 {u'build_id': 63357224, u'status': 0, u'branch': u'releases/mozilla-beta', u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_by_name': u'buildbot-master74.bb.releng.usw2.mozilla.com:/builds/buildbot/build1/master', u'buildnumber': 0, u'starttime': 1424276543, u'requests': [{u'complete_at': 1424283655, u'complete': 1, u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_at': 1424283079, u'priority': 0, u'submittime': 1424276528, u'reason': u'scheduler', u'branch': u'releases/mozilla-beta', u'request_id': 62220517, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}], u'endtime': 1424283655, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}
02/18/2015 04:33:07 DEBUG:	 We found a successful job. We don't search anymore.
02/18/2015 04:33:07 DEBUG:	 There is a job that has completed successfully.
02/18/2015 04:33:07 DEBUG:	 {u'build_id': 63357224, u'status': 0, u'branch': u'releases/mozilla-beta', u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_by_name': u'buildbot-master74.bb.releng.usw2.mozilla.com:/builds/buildbot/build1/master', u'buildnumber': 0, u'starttime': 1424276543, u'requests': [{u'complete_at': 1424283655, u'complete': 1, u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_at': 1424283079, u'priority': 0, u'submittime': 1424276528, u'reason': u'scheduler', u'branch': u'releases/mozilla-beta', u'request_id': 62220517, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}], u'endtime': 1424283655, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}
02/18/2015 04:33:07 DEBUG:	 Job identified with complete_at value: 1424283655 run on 2015-02-18
02/18/2015 04:33:10 DEBUG:	 We are going to look for 62220517 through the jobs run on 2015-02-18.
02/18/2015 04:33:10 ERROR:	 We have not found the job. If you see this problem please send us the log with--debug and --dry-run.
02/18/2015 04:33:10 ERROR:	 If this does not work please file a bug and send us the complete output.
Traceback (most recent call last):
  File "alltalos.py", line 110, in <module>
    main()
  File "alltalos.py", line 106, in main
    dry_run=options.dry_run)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 259, in trigger_job
    buildername,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 92, in _determine_trigger_objective
    files = _find_files(successful_job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 126, in _find_files
    "We should not have received an empty status"
AssertionError: We should not have received an empty status

I have hacked platforms.py to remove pgo- from the buildername, and it gets me the proper build.

**Comment by armenzg** [comment]
Can I assume the other issue you filed is what we're seeing here?

**Comment by armenzg** [comment]
Can we close this?

**Comment by jmaher** [comment]
using the bisection branch, I run this command and get an error:
python trigger.py  --repo-name mozilla-beta --rev 948a2c2e31d4 -b "Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez" --debug --dry-run
02/19/2015 01:32:27 INFO:	 Setting DEBUG level
02/19/2015 01:32:27 DEBUG:	 We want to trigger 'Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez' on revision '948a2c2e31d4' a total of 1 times.
02/19/2015 01:32:27 DEBUG:	 Buildername Ubuntu HW 12.04 x64 mozilla-beta pgo talos chromez is valid.
02/19/2015 01:32:27 DEBUG:	 Buildername Linux x86-64 mozilla-beta build is valid.
02/19/2015 01:32:27 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-beta/rev/948a2c2e31d4?format=json
02/19/2015 01:32:27 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
02/19/2015 01:32:28 DEBUG:	 "GET /buildapi/self-serve/mozilla-beta/rev/948a2c2e31d4?format=json HTTP/1.1" 200 19160
02/19/2015 01:32:28 DEBUG:	 Find jobs matching 'Linux x86-64 mozilla-beta build'
02/19/2015 01:32:28 DEBUG:	 We have matched 1 jobs.
02/19/2015 01:32:28 DEBUG:	 List of matching jobs:
02/19/2015 01:32:28 DEBUG:	 {u'build_id': 63357224, u'status': 0, u'branch': u'releases/mozilla-beta', u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_by_name': u'buildbot-master74.bb.releng.usw2.mozilla.com:/builds/buildbot/build1/master', u'buildnumber': 0, u'starttime': 1424276543, u'requests': [{u'complete_at': 1424283655, u'complete': 1, u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_at': 1424283079, u'priority': 0, u'submittime': 1424276528, u'reason': u'scheduler', u'branch': u'releases/mozilla-beta', u'request_id': 62220517, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}], u'endtime': 1424283655, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}
02/19/2015 01:32:28 DEBUG:	 We found a successful job. We don't search anymore.
02/19/2015 01:32:28 DEBUG:	 There is a job that has completed successfully.
02/19/2015 01:32:28 DEBUG:	 {u'build_id': 63357224, u'status': 0, u'branch': u'releases/mozilla-beta', u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_by_name': u'buildbot-master74.bb.releng.usw2.mozilla.com:/builds/buildbot/build1/master', u'buildnumber': 0, u'starttime': 1424276543, u'requests': [{u'complete_at': 1424283655, u'complete': 1, u'buildername': u'Linux x86-64 mozilla-beta build', u'claimed_at': 1424283079, u'priority': 0, u'submittime': 1424276528, u'reason': u'scheduler', u'branch': u'releases/mozilla-beta', u'request_id': 62220517, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}], u'endtime': 1424283655, u'revision': u'948a2c2e31d4b7eaa282ddeb327708605e3cc7fa'}
02/19/2015 01:32:28 DEBUG:	 Job identified with complete_at value: 1424283655 run on 2015-02-18
02/19/2015 01:32:31 DEBUG:	 We are going to look for 62220517 through the jobs run on 2015-02-18.
02/19/2015 01:32:31 ERROR:	 We have not found the job. If you see this problem please send us the log with--debug and --dry-run.
02/19/2015 01:32:31 ERROR:	 If this does not work please file a bug and send us the complete output.
Traceback (most recent call last):
  File "trigger.py", line 61, in <module>
    main()
  File "trigger.py", line 47, in main
    dry_run=args.dry_run
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 259, in trigger_job
    buildername,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 92, in _determine_trigger_objective
    files = _find_files(successful_job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 126, in _find_files
    "We should not have received an empty status"
AssertionError: We should not have received an empty status

**Comment by armenzg** [comment]
Do you still hit this issue? I can't hit it after my last push.

**Comment by jmaher** [comment]
with the latest update, this appears to be fixed.
