### ISSUE TITLE
Provide means to trigger jobs defined by TH filter N times

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#182]
<jgraham> is there a plan to provide a high-level interface for common tasks like e.g. "trigger all jobs matching a treherder filter N times on a specific revision"?
So I could do something like https://treeherder.mozilla.org/#/jobs?repo=cedar&revision=065f57c91e7f&filter-searchStr=web-platform%20debug from the command line without having to look up the builder names ever

We should discuss that with the TH team.

We should also consider how to treat filters where builds jobs are shown since we don't want to trigger a build job N times unless that is our intended desire.
Sometimes some filters show us more jobs than we intend to trigger.

**Comment by vaibhavmagarwal** [comment]
Closing this issue since we have triggerbyfilters.py script.
