### ISSUE TITLE
mozci should use a mozci named logger instead of the root logger

### ISSUE THREAD

**Issue by parkouss** [armenzg/mozilla_ci_tools#186]
I use mozci as a library for a new tool (https://github.com/parkouss/mozbattue), and I use the info log statements of mozci (which are useful!).
It would be good to be able to distinguish the log of my application from the logs of mozci. Something like LOG = logging.getLogger('mozci') in mozci code would be great!

**Comment by armenzg** [comment]
I pushed a fix for this.
Please let us know if it meets what you need.
Would you need a release?

**Comment by parkouss** [comment]
Awesome, thank you! A new release would be cool, but this is not urgent.
