### ISSUE TITLE
Do not fix libraries versions in the setup.py

### ISSUE THREAD

**Issue by parkouss** [armenzg/mozilla_ci_tools#188]
Hm, I have a strange bug. I have one application that is using mozci and bugsi: https://github.com/parkouss/mozbattue/blob/master/setup.py

Pip can not install these properly (I tried pip 6.0.7 and latest 6.1.1): https://travis-ci.org/parkouss/mozbattue/builds/62225972

It seems that if I run "pip install mozci" after the issue, all is running fine. I looked into mozci's setup.py script, and there is bugsy listed as a dependency (with a fixed version).

This seems like a pip bug - still I'm not 100% sure as I did not checked every requirement of every dependencies recursively.

However I think that it may be good to not fix versions this way in mozci - as it is intended to be used as a library, this could easily conflict with other libraries dependencies or one of the program dependencies itself. Maybe something like "bugsy>=0.4" and "requests>=2.5.1" would be a good solution? This is a proposal, and I can understand if you find this too risky. :)

I think that should fix my problem - note that I could also do not make bugsy a dependency, and hope that future mozci versions will still use bugsy. This is an open-to-discussion issue!

**Comment by armenzg** [comment]
Do you want to give it a shot and let me know how it goes?

I think we could loosen up the requirements if it proves to help you.

**Comment by parkouss** [comment]
Hm, this really seems to be a pip bug somewhere, or at least something I don't understand now. I am not able to reproduce it with
pip install mozci bugsy && pip install -e .
but only when I run pip install -e .
(each command in a fresh virtualenv, done in my cloned dir). So this is really strange, and I'm not sure that not fixing the version would help now. I think that for my need here, I will only make a dependency on mozci (this works for each command) - and I will inherit the bugsy dependency anyway.

So you can close this issue - unless you'd want to take the opportunity to not fix the versions.

**Comment by vaibhavmagarwal** [comment]
I think older versions of requests and pip have conflicts.
@parkouss Same error as you got: https://github.com/docker/compose/issues/918
Also check: https://github.com/pypa/pip/issues/775

**Comment by vaibhavmagarwal** [comment]
I think this is really not a mozci problem, at most we can upgrade requests version in setup.py

**Comment by parkouss** [comment]
Thanks @vaibhavmagarwal for looking into this. :) So yes, sounds like a pip bug;

I suspect that if "requests >= 2.5.1" is specified in mozci, it won't fail anymore for me - but it won't work if you specify something like "requests == 2.5.3".

It seems that pip look at the dependency in bugsy (which is "requests >= 1.1"), download the latest version (2.7.0) and exit... At runtime, I get the exception noted in comment 2. If I remove my main dependency bugsy (leaving mozci alone) everything goes well (and requests 2.5.1 is installed).

So it's up to you - if you accept to change your requests dependency (with no upper version limit) it will fix my problem - else I can remove bugsy from my dependencies to fix the bug, or I suspect that I can add requests as my direct dependencies as a workaround (even if I don't use it). Tell me what you want to do :)

**Comment by armenzg** [comment]
I'm happy to loose requests.

**Comment by parkouss** [comment]
Cool! So just to be clear, the bug is well explained here: https://github.com/pypa/pip/issues/988.
As I have the following dependencies:
- mozci
  - requests == 2.5.1
- bugzy
  - requests >= 1.1.1

pip (for sub dependencies) will just apply "first found wins"... In that case, "requests >= 1.1.1". And that will just allow to download the latest requests. This does not match with the mozci requests requirements, so I got pkg_resources.ContextualVersionConflict exception at runtime.

**Comment by vaibhavmagarwal** [comment]
This should now be fixed. Reopen if any problems.
