### ISSUE TITLE
when we don't build a platform, mozilla_ci doesn't trigger the build

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#19]
taking a push when we add DONTBUILD in the commit message:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=991c40f00898

we end up with no builds/tests for the push, but when trying to backfill, we get:

python trigger.py  --dry-run --debug --repo-name mozilla-inbound --rev 991c40f00898 -b "Ubuntu HW 12.04 mozilla-inbound talos chromez"
02/18/2015 04:46:00 INFO:	 Setting DEBUG level
02/18/2015 04:46:00 DEBUG:	 We want to trigger 'Ubuntu HW 12.04 mozilla-inbound talos chromez' on revision '991c40f00898' a total of 1 times.
02/18/2015 04:46:00 DEBUG:	 Buildername Ubuntu HW 12.04 mozilla-inbound talos chromez is valid.
02/18/2015 04:46:00 DEBUG:	 The build job that triggers Ubuntu HW 12.04 mozilla-inbound talos chromez is Linux mozilla-inbound build
02/18/2015 04:46:00 DEBUG:	 Buildername Linux mozilla-inbound build is valid.
02/18/2015 04:46:00 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/991c40f00898?format=json
02/18/2015 04:46:00 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
02/18/2015 04:46:01 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/991c40f00898?format=json HTTP/1.1" 404 103
02/18/2015 04:46:01 DEBUG:	 Find jobs matching 'Linux mozilla-inbound build'
Traceback (most recent call last):
  File "trigger.py", line 61, in <module>
    main()
  File "trigger.py", line 47, in main
    dry_run=args.dry_run
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 259, in trigger_job
    buildername,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 54, in _determine_trigger_objective
    matching_jobs = _matching_jobs(build_buildername, all_jobs)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 29, in _matching_jobs
    if j["buildername"] == buildername:
TypeError: string indices must be integers
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/scripts$ 

I think we should not build by default on these cases, but not error out.  this will fail if we have a range of commits where one of the commits hits this failure condition.  Ideally we could have a flag that mozci accepts to force builds.

**Comment by armenzg** [comment]
I will work on this.

**Comment by armenzg** [comment]
Let me know if you cannot verify the fix. Re-open if so.

I have this fix (plus some refactoring) in both master and bisection:
https://github.com/armenzg/mozilla_ci_tools/commit/fcb819542872ac1f1b04c61ed0f1b3d868e596e3

armenzg@armenzg-thinkpad:~/repos/ci_tools$ python scripts/trigger.py --repo-name mozilla-inbound --rev 991c40f00898 -b "Ubuntu HW 12.04 mozilla-inbound talos chromez"
02/19/2015 04:35:17 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
02/19/2015 04:35:19 INFO:	 We will _NOT_ trigger anything for revision 991c40f00898 for mozilla-inbound since it does not exist in self-serve.

**Comment by jmaher** [comment]
verified!
