### ISSUE TITLE
Expose a simple triggering API with minimal hazards for external consumers

### ISSUE THREAD

**Issue by chmanchester** [armenzg/mozilla_ci_tools#191]
I'd like to use mozCI for a pulse service that retriggers jobs, but I have a few concerns with the current API, primarily needing to clean up files if they're downloaded as a data source and wanting to be able to authenticate from outside mozCI to make use of its methods.

We can authenticate on any machine using mozCI and the credentials will be stored, which should work ok. @armenzg also pointed out that we can call buildapi.make_request directly without fear of downloading files as a result of calling it.

The only part I'm still concerned about is getting guarantees about the exceptions that might propagate from calling a function (make_request has an assert statement in it, which we could check for, but we want this to be stable).

**Comment by armenzg** [comment]
With regard to the data stored under ~/.mozilla/mozci, is your concern running out of space on a VM?
In general, we could make buildjson files older than a month to be automatically delete without your maintenance if that would help.
Storing on disk helps a lot for other purposes of mozci, however, if wanted we could also not store any data.

With regards to authentication, once the credentials are stored (username in credentials.cfg and *encrypted* password in keyring), what specifically are you facing? We don't prompt anymore the user if we have indicated that we're OK storing the credentials. Even in follow up runs.
I think I'm failling to grasp the issue.

I think we can easily verify that raising the exception should not cause any issues.
chmanchester is referring specifically to https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L62

**Comment by chmanchester** [comment]
My concern with the data downloaded is indeed running out of space, and potentially performance if we encounter a situation where what we're doing is blocked on a download (although I'd have to see this in action to actually say it's an issue).

For authentication, this is mostly a matter of convenience. If I've written a tool that needs to manage authentication itself, it seems inconvenient to additionally need to authenticate at the machine level for mozCI.

Regarding exceptions (this is also not a blocker, but worth discussing), what I want is some idea that a certain call to a method in mozCI can only raise a certain set of exceptions, and that this is unlikely to change over time.

**Comment by chmanchester** [comment]
My concern with the data downloaded is indeed running out of space, and potentially performance if we encounter a situation where what we're doing is blocked on a download (although I'd have to see this in action to actually say it's an issue).

For authentication, this is mostly a matter of convenience. If I've written a tool that needs to manage authentication itself, it seems inconvenient to additionally need to authenticate at the machine level for mozCI.

Regarding exceptions (this is also not a blocker, but worth discussing), what I want is some idea that a certain call to a method in mozCI can only raise a certain set of exceptions, and that this is unlikely to change over time.

**Comment by armenzg** [comment]
With regards to file sizes, we're switching to store the files gzip'ed.

We have added authentication through environment variables.

adusca is looking into adding a set stable exceptions.

**Comment by vaibhavmagarwal** [comment]
I have merged https://github.com/armenzg/mozilla_ci_tools/pull/282 to cleanup very old buildjson files, let me know if this issue is fixed with that pr.

**Comment by armenzg** [comment]
The only work left is to switch assertions to established exceptions.

**Comment by adusca** [comment]
Depends on: #248

**Comment by armenzg** [comment]
@nikkisquared fixed this
