### ISSUE TITLE
Deprecate alltalos.py with triggerbyfilters.py if possible

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#206]
As discussed in:
https://github.com/armenzg/mozilla_ci_tools/pull/198

**Comment by armenzg** [comment]
We should make --exclude 'pgo' by default in most places.

The filters should also allow to either specify "Android" versus "android".

triggerbyfilters.py should allow using --dry-run and give a summary at the end as to what builders where going to be triggered so developers can inspect it. This is a scope creep so we might want a new issue for it.

**Comment by adusca** [comment]
In triggerbyfilters.py, we could default to 'opt' if neither 'opt', 'debug' or 'pgo' is specified in --includes, but that would break the use-case of wanting to trigger all job types. That also doesn't work for mozilla-aurora and mozilla-beta (m-a/m-b valid buildernames are pgo jobs that don't include 'opt', 'pgo' or 'debug' in their names)

alltalos.py knows how to deal with mozilla-aurora and mozilla-beta, triggerbyfilters.py doesn't. If someone tried:
python triggerbyfilters.py mozilla-aurora REVISION -i talos

It would end up trying to trigger "Ubuntu HW 12.04 mozilla-aurora pgo talos chromez", and that's not a valid job. It would work if we excluded everything with 'pgo', but excluding 'pgo' in a pgo-only branch is very confusing.

**Comment by vaibhavmagarwal** [comment]
Fixed in https://github.com/armenzg/mozilla_ci_tools/pull/324
