### ISSUE TITLE
Represent jobs as objects

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#21]
We currently simply grab the data returned by the releng systems and expect people to figure out how to manipulate the data.

If we created a class representing jobs we would make it easier to produce up-to-date documentation and manipulation.

This is a low priority.

**Comment by vaibhavmagarwal** [comment]
This issue does not make sense to me now (heh). @armenzg did you meant that we should have object-orientation? If that is the case, we do have BuildApi and Treeherder classes in query_jobs.py

**Comment by armenzg** [comment]
Yes, query_jobs was in that direction.
It was mainly that the data coming from the various APIs are normally json objects or directionaries which could be better represented (by only grabbing the pieces which are relevant and making attributes of an object).

Even this, it is an example of it:
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/scheduling.py

This is not important enough.
