### ISSUE TITLE
IOError: CRC check failed - happens quite often (5 times today already)

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#213]
Traceback (most recent call last):
  File "triggerbyfilters.py", line 108, in <module>
    main()
  File "triggerbyfilters.py", line 97, in main
    dry_run=options.dry_run,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 415, in trigger_range
    files=files)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 344, in trigger_job
    buildername,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 132, in _determine_trigger_objective
    files = _find_files(job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 188, in _find_files
    job_status = _status_info(job_schedule_info)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 181, in _status_info
    return buildjson.query_job_data(complete_at, request_id)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 146, in query_job_data
    job = _find_job(request_id, _fetch_data(BUILDS_4HR_FILE), BUILDS_4HR_FILE)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 42, in _fetch_data
    json_contents = load_file(filepath, url)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/utils/transfer.py", line 156, in load_file
    return _fetch_and_load_file(req, filepath)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/utils/transfer.py", line 87, in _fetch_and_load_file
    blob = gzipper.read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x3d16ffd8 != 0x9fa335b8L

**Comment by jmaher** [comment]
and the magical commandline:
python triggerbyfilters.py --times 2 -i mochitest -e devtools,chrome,other,android,b2g,pgo,10.8,Code try e3c7e03823c5

**Comment by armenzg** [comment]
I backed out the code that caused this: https://github.com/armenzg/mozilla_ci_tools/commit/5d4bef36b4b0a673b974976c851ac601bbf869be

**Comment by armenzg** [comment]
Let's catch it and retry.

From today:
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/mozci/scripts$ python triggerbyfilters.py -i untu,talos,pgo --times 5 mozilla-central ac277e615f8f
26 jobs will be triggered, do you wish to continue? y/n/d (d=show details) d
05/20/2015 12:57:59 INFO:	 The following jobs will be triggered: 
 Ubuntu HW 12.04 mozilla-central pgo talos chromez
Ubuntu HW 12.04 mozilla-central pgo talos chromez-e10s
Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs
Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs-e10s
Ubuntu HW 12.04 mozilla-central pgo talos g1
Ubuntu HW 12.04 mozilla-central pgo talos g1-e10s
Ubuntu HW 12.04 mozilla-central pgo talos g2
Ubuntu HW 12.04 mozilla-central pgo talos other-e10s_nol64
Ubuntu HW 12.04 mozilla-central pgo talos other_nol64
Ubuntu HW 12.04 mozilla-central pgo talos svgr
Ubuntu HW 12.04 mozilla-central pgo talos svgr-e10s
Ubuntu HW 12.04 mozilla-central pgo talos tp5o
Ubuntu HW 12.04 mozilla-central pgo talos tp5o-e10s
Ubuntu HW 12.04 x64 mozilla-central pgo talos chromez
Ubuntu HW 12.04 x64 mozilla-central pgo talos chromez-e10s
Ubuntu HW 12.04 x64 mozilla-central pgo talos dromaeojs
Ubuntu HW 12.04 x64 mozilla-central pgo talos dromaeojs-e10s
Ubuntu HW 12.04 x64 mozilla-central pgo talos g1
Ubuntu HW 12.04 x64 mozilla-central pgo talos g1-e10s
Ubuntu HW 12.04 x64 mozilla-central pgo talos g2
Ubuntu HW 12.04 x64 mozilla-central pgo talos other-e10s_l64
Ubuntu HW 12.04 x64 mozilla-central pgo talos other_l64
Ubuntu HW 12.04 x64 mozilla-central pgo talos svgr
Ubuntu HW 12.04 x64 mozilla-central pgo talos svgr-e10s
Ubuntu HW 12.04 x64 mozilla-central pgo talos tp5o
Ubuntu HW 12.04 x64 mozilla-central pgo talos tp5o-e10s
Do you wish to continue? y/n y
05/20/2015 12:58:06 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos chromez on revisions ['ac277e615f8f']
05/20/2015 12:58:06 INFO:	 
05/20/2015 12:58:06 INFO:	 === ac277e615f8f ===
05/20/2015 12:58:10 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos chromez on revision ac277e615f8f
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:10   1.17 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:09   1.30 MB/s 11.0MB
05/20/2015 12:58:39 INFO:	 We have found 2 potential job(s) matching 'Ubuntu HW 12.04 mozilla-central pgo talos chromez' on ac277e615f8f. We need to trigger more.
05/20/2015 12:58:39 INFO:	 We want to trigger 'Ubuntu HW 12.04 mozilla-central pgo talos chromez' on revision 'ac277e615f8f' a total of 3 time(s).
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:06   1.76 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:07   1.70 MB/s 11.0MB
05/20/2015 12:59:03 INFO:	 There is a _build_ job that has completed successfully.
05/20/2015 12:59:03 INFO:	 We have the necessary files to trigger the downstream job.
05/20/2015 12:59:05 INFO:	 https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&fromchange=ac277e615f8f&tochange=ac277e615f8f&filter-searchStr=Ubuntu+HW+12.04+mozilla-central+pgo+talos+chromez
05/20/2015 12:59:05 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos chromez-e10s on revisions ['ac277e615f8f']
05/20/2015 12:59:05 INFO:	 
05/20/2015 12:59:05 INFO:	 === ac277e615f8f ===
05/20/2015 12:59:06 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos chromez-e10s on revision ac277e615f8f
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:08   1.40 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:06   1.75 MB/s 11.0MB
05/20/2015 12:59:30 INFO:	 We have found 2 potential job(s) matching 'Ubuntu HW 12.04 mozilla-central pgo talos chromez-e10s' on ac277e615f8f. We need to trigger more.
05/20/2015 12:59:30 INFO:	 We want to trigger 'Ubuntu HW 12.04 mozilla-central pgo talos chromez-e10s' on revision 'ac277e615f8f' a total of 3 time(s).
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:06   1.72 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:06   1.75 MB/s 11.0MB
05/20/2015 12:59:54 INFO:	 There is a _build_ job that has completed successfully.
05/20/2015 12:59:54 INFO:	 We have the necessary files to trigger the downstream job.
05/20/2015 12:59:55 INFO:	 https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&fromchange=ac277e615f8f&tochange=ac277e615f8f&filter-searchStr=Ubuntu+HW+12.04+mozilla-central+pgo+talos+chromez-e10s
05/20/2015 12:59:55 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs on revisions ['ac277e615f8f']
05/20/2015 12:59:55 INFO:	 
05/20/2015 12:59:55 INFO:	 === ac277e615f8f ===
05/20/2015 12:59:56 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs on revision ac277e615f8f
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:08   1.43 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:14 841.33 kB/s 11.0MB
05/20/2015 01:00:27 INFO:	 We have found 2 potential job(s) matching 'Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs' on ac277e615f8f. We need to trigger more.
05/20/2015 01:00:27 INFO:	 We want to trigger 'Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs' on revision 'ac277e615f8f' a total of 3 time(s).
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:07   1.61 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:07   1.59 MB/s 11.0MB
05/20/2015 01:00:52 INFO:	 There is a _build_ job that has completed successfully.
05/20/2015 01:00:52 INFO:	 We have the necessary files to trigger the downstream job.
05/20/2015 01:00:53 INFO:	 https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&fromchange=ac277e615f8f&tochange=ac277e615f8f&filter-searchStr=Ubuntu+HW+12.04+mozilla-central+pgo+talos+dromaeojs
05/20/2015 01:00:53 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs-e10s on revisions ['ac277e615f8f']
05/20/2015 01:00:53 INFO:	 
05/20/2015 01:00:53 INFO:	 === ac277e615f8f ===
05/20/2015 01:00:54 INFO:	 We want to have 5 job(s) of Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs-e10s on revision ac277e615f8f
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:07   1.68 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:07   1.70 MB/s 11.0MB
05/20/2015 01:01:17 INFO:	 We have found 2 potential job(s) matching 'Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs-e10s' on ac277e615f8f. We need to trigger more.
05/20/2015 01:01:17 INFO:	 We want to trigger 'Ubuntu HW 12.04 mozilla-central pgo talos dromaeojs-e10s' on revision 'ac277e615f8f' a total of 3 time(s).
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:07   1.70 MB/s 11.0MB
builds-2015-05-20.js: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] Elapsed Time: 0:00:07   1.56 MB/s 11.0MB
Traceback (most recent call last):
  File "triggerbyfilters.py", line 108, in <module>
    main()
  File "triggerbyfilters.py", line 97, in main
    dry_run=options.dry_run,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 415, in trigger_range
    files=files)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 344, in trigger_job
    buildername,
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 132, in _determine_trigger_objective
    files = _find_files(job)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 188, in _find_files
    job_status = _status_info(job_schedule_info)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/mozci.py", line 181, in _status_info
    return buildjson.query_job_data(complete_at, request_id)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 152, in query_job_data
    job = _find_job(request_id, _fetch_data(filename), filename)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/sources/buildjson.py", line 42, in _fetch_data
    json_contents = load_file(filepath, url)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/utils/transfer.py", line 147, in load_file
    return _fetch_and_load_file(req, filepath)
  File "/home/jmaher/mozilla/mozilla_ci_tools/mozci/utils/transfer.py", line 78, in _fetch_and_load_file
    blob = gzipper.read()
  File "/usr/lib/python2.7/gzip.py", line 254, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xa25041c7 != 0xd4d23656L
jmaher@jmaher-ThinkPad-X230:~/mozilla/mozilla_ci_tools/mozci/scripts$

**Comment by adusca** [comment]
Fixed on #267. Now we try again when we get a corrupted file.
