### ISSUE TITLE
when a build fails a check we can run tests, mozci tries to schedule a new build

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#219]
I am trying to schedule win8 mochitest-2 on a range of builds, this is easy to do normally, but when the range of builds have a build failure mozci tries to schedule a build.

There is a problem though.  Many times a build completes and generates a firefox.zip|exe|tar and we schedule and run unittests.  When we have a valid binary + tests package we should schedule tests.

On the other hand, if a build fails there is probably a real problem.  We don't want to be scheduling builds if one has failed, there is probably a good reason for it failing.  Sometimes a failure is a hiccup, but normally in that case the sheriffs or someone would have retriggered it.

Here is a view of the builders:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&fromchange=d0129aa5b896&tochange=6afb088b0cff&filter-searchStr=windows%208%20x64%20build

**Comment by armenzg** [comment]
adusca says that she would like to look into this.

**Comment by armenzg** [comment]
https://github.com/armenzg/mozilla_ci_tools/pull/220
