### ISSUE TITLE
New job doesn't get started if one already exists

### ISSUE THREAD

**Issue by mnoorenberghe** [armenzg/mozilla_ci_tools#222]
`mozci-trigger --rev 08138045c38c -b "Rev4 MacOSX Snow Leopard 10.6 try opt test mochitest-browser-chrome-2" --file https://ftp.mozilla.org/pub/mozilla.org/firefox/try-builds/mozilla@noorenberghe.ca-08138045c38c/try-macosx64/firefox-41.0a1.en-US.mac.dmg --file https://people.mozilla.org/~mnoorenberghe/tmp/firefox-41.0a1.en-US.mac64.tests.zip`

Leads to
`We want to have 1 job(s) of Rev4 MacOSX Snow Leopard 10.6 try opt test mochitest-browser-chrome-2 on revision 08138045c38c`
…
`We have 1 job(s) for 'Rev4 MacOSX Snow Leopard 10.6 try opt test mochitest-browser-chrome-2' which is enough for the 1 job(s) we want.`

This job was already triggered once via try chooser syntax but I don't see why it didn't trigger another job. The default IMO should be to trigger one more of the job (especially since I'm pointing to a different tests.zip).

In a related matter, I think the documentation for --times is inaccurate:
`--times TIMES         Number of times to retrigger the push.`
When I got the above error I specified `--times 2` and it only added one job to the existing one I had yet the description says "retrigger" where the re- prefix implies that it's going to add 2 more triggers.

**Comment by armenzg** [comment]
Thanks Matt.
With regards to the documentation, we have to fix that. Thanks for pointing it out.

With regards to the jobs that we need to trigger, it is a very specific case you're looking into and I wonder how it would best work with other cases.
If we think of the case where we're looking at a range of revisions (e.g. backfilling on mozilla-inbound), the number of jobs across revisions is variable. In some we would have 0 on some we would have 1 and all we want is 1 job per revision.

Would an alternative flag help? For instance, --extra-runs? This would add extra jobs regardless of how many are already running or completed. I think, we should probably have an upper-limit to avoid issues of misuse.

@jmaher you're a heavy user of mozci; what are your thoughts on this?

**Comment by jmaher** [comment]
I think there are two things here, trigger and retrigger.  There are cases where it is important to have 5 instances, and there are other cases where I want 5 more instances.

what makes the best default- I am not sure.  Take for example sheriffs backfilling coalesced jobs, they want to trigger with --times=1 and it would ensure that each job is run once (to be technical, each job is run green once).  For talos or other investigation, I want to add 5 or 10 retriggers (:mattn's case in this issue).

when the script is called trigger.py (or triggerbyfilter.py), then we imply that we are triggering a job.  if we add a --retrigger command, that would imply do it and ignore how many previous instances exist.

we should address the issue of job state as well.  Lets say you have a perma fail and you want 3 instances, so the first time it fails, and some tool auto triggers 2 more instances resulting in 3 failures.  Lets assume this tool ran again in a cron job until it had 3 green instances- then we would be in a crazy loop.  I think it is safe to assume we have green jobs and limit it to 100 instances unless specified.

Those are some thoughts for fun!

**Comment by armenzg** [comment]
@mnoorenberghe would a --retrigger flag work for you?

**Comment by mnoorenberghe** [comment]
I think so as long as we make the behaviour (including `--times`) with and without clear.
