### ISSUE TITLE
_fetch_and_load_file is only caching compressed downloads, in uncompressed form

### ISSUE THREAD

**Issue by glandium** [armenzg/mozilla_ci_tools#227]
In b584fcc087340cc1b2d1fa640841354973c4ac42, I removed one level of indentation that 5e9f2cecf5b7cb1102505f32b4876d6b192a0be2 added. Looking further, that was already one level of indentation too much before that: the cache is only stored if the requested file has x-gzip Content-Encoding. It also only does that only for non-windows, so Windows does not cache at all.
The cache is also stored uncompressed, which for builds-4hrs.gz is 30M instead of 3M.
And in fact, _fetch_and_load_file will throw an UnboundLocalError exception when the downloaded file doesn't have a x-gzip Content-Encoding because json_content is only set if it does.

**Comment by glandium** [comment]
Let me clean this up after lunch.

**Comment by adusca** [comment]
Fixed in #229.
