### ISSUE TITLE
Do not allow to trigger abitrary job for a downstream type of job *without* test files (aka test jobs)

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#230]
Ryan showed me this:
https://treeherder.mozilla.org/logviewer.html#?job_id=10271595&repo=mozilla-inbound

The question to answer, how did we schedule a job without specifying the files?
We should prevent mozci from ever doing that for downstream jobs (files can currently be [] for build builders):
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L42

Somehow he triggered once a job without files [1]:
{'files': [], 'priority': 0, 'builder_name': 'Windows XP 32-bit mozilla-inbound debug test crashtest', 'branch': 'mozilla-inbound-selfserve', 'properties': {}, 'revision': '197a7c20143d'}
BODY:
{'body': {'msg': 'Ok', 'errors': False}, 'request_id': 1341351}

After that he triggered it with files:
{'files': ['http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-win32-debug/1432908942/firefox-41.0a1.en-US.win32.zip', 'http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-win32-debug/1432908942/firefox-41.0a1.en-US.win32.tests.zip', 'http://ftp.mozilla.org/pub/mozilla.org/firefox/tinderbox-builds/mozilla-inbound-win32-debug/1432908942/firefox-41.0a1.en-US.win32.crashreporter-symbols.zip'], 'priority': 0, 'builder_name': 'Windows XP 32-bit mozilla-inbound debug test crashtest', 'branch': 'mozilla-inbound-selfserve', 'properties': {}, 'revision': '197a7c20143d'}
BODY:
{'body': {'msg': 'Ok', 'errors': False}, 'request_id': 1341357}

However mozci, re-triggered the job **without** files.

[1] https://secure.pub.build.mozilla.org/buildapi/self-serve/jobs

**Comment by vaibhavmagarwal** [comment]
Comparing the files when this issue was filed: https://github.com/armenzg/mozilla_ci_tools/blob/2d822a38a292de7b423da40e9d15be8cc08a7852/mozci/mozci.py#L205 vs now:
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/mozci.py#L238
We now also check for "testPackagesUrl", so this issue should not occur. @armenzg thoughts?

**Comment by armenzg** [comment]
Let's close it for now. Thanks @vaibhavmagarwal
