### ISSUE TITLE
We can't determine the files for a running job

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#232]
Alice is looking into it.
We try look for files for a running job which has triggered test jobs, however, it has not completed and I don't think we can grab the files from it.
We should patch fix it so we don't try for running jobs OR we inspect any of the downstream jobs which are either scheduled or running.
In this exact moment, the debug crashtest has not been scheduled:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=f7c43c293359&filter-searchStr=windows%20xp%2032-bit%20mozilla-inbound%20debug
Some other debug test jobs are currently running.

(ci_tools)MacAir ci_tools git:[master] $ mozci-trigger -r f7c43c293359 -b "Windows XP 32-bit mozilla-inbound debug test crashtest" --times 25 --debug --dry-run
05/29/2015 03:02:27 INFO:	 Setting DEBUG level
05/29/2015 03:02:27 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
05/29/2015 03:02:28 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
05/29/2015 03:02:28 DEBUG:	 Loading /Users/armenzg/.mozilla/mozci/repositories.txt
05/29/2015 03:02:28 DEBUG:	 Determine repository associated to mozilla-inbound
05/29/2015 03:02:28 INFO:	 We want to have 25 job(s) of Windows XP 32-bit mozilla-inbound debug test crashtest on revisions ['f7c43c293359']
05/29/2015 03:02:28 INFO:
05/29/2015 03:02:28 INFO:	 === f7c43c293359 ===
05/29/2015 03:02:28 DEBUG:	 Determine if the revision is valid in buildapi.
05/29/2015 03:02:28 DEBUG:	 Loading LDAP user from /Users/armenzg/.mozilla/credentials.cfg
05/29/2015 03:02:28 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
05/29/2015 03:02:29 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/f7c43c293359?format=json HTTP/1.1" 200 17967
05/29/2015 03:02:29 INFO:	 We want to have 25 job(s) of Windows XP 32-bit mozilla-inbound debug test crashtest on revision f7c43c293359
05/29/2015 03:02:29 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/f7c43c293359?format=json
05/29/2015 03:02:29 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
05/29/2015 03:02:30 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/f7c43c293359?format=json HTTP/1.1" 200 17925
05/29/2015 03:02:30 DEBUG:	 Find jobs matching 'Windows XP 32-bit mozilla-inbound debug test crashtest'
05/29/2015 03:02:30 DEBUG:	 We have found 0 job(s) of 'Windows XP 32-bit mozilla-inbound debug test crashtest'.
05/29/2015 03:02:30 DEBUG:	 We found 0 pending jobs, 0 running jobs and 0 successful_jobs.
05/29/2015 03:02:30 INFO:	 We have found 0 potential job(s) matching 'Windows XP 32-bit mozilla-inbound debug test crashtest' on f7c43c293359. We need to trigger more.
05/29/2015 03:02:30 INFO:	 We want to trigger 'Windows XP 32-bit mozilla-inbound debug test crashtest' on revision 'f7c43c293359' a total of 25 time(s).
05/29/2015 03:02:30 DEBUG:	 Buildername Windows XP 32-bit mozilla-inbound debug test crashtest is valid.
05/29/2015 03:02:30 DEBUG:	 Computing builders' relations from allthethings data.
05/29/2015 03:02:30 DEBUG:	 Buildername WINNT 5.2 mozilla-inbound leak test build is valid.
05/29/2015 03:02:30 DEBUG:	 Find jobs matching 'WINNT 5.2 mozilla-inbound leak test build'
05/29/2015 03:02:30 DEBUG:	 We have found 1 job(s) of 'WINNT 5.2 mozilla-inbound leak test build'.
05/29/2015 03:02:30 DEBUG:	 List of matching jobs:
05/29/2015 03:02:30 DEBUG:	 Asking for job data - request_id: 71000436 & complete_at: None
05/29/2015 03:02:30 ERROR:
Traceback (most recent call last):
  File "/Users/armenzg/venv/ci_tools/lib/python2.7/site-packages/mozci/scripts/trigger.py", line 189, in main
    files=options.files
  File "/Users/armenzg/venv/ci_tools/lib/python2.7/site-packages/mozci/mozci.py", line 439, in trigger_range
    files=files)
  File "/Users/armenzg/venv/ci_tools/lib/python2.7/site-packages/mozci/mozci.py", line 352, in trigger_job
    buildername,
  File "/Users/armenzg/venv/ci_tools/lib/python2.7/site-packages/mozci/mozci.py", line 122, in _determine_trigger_objective
    files = _find_files(job)
  File "/Users/armenzg/venv/ci_tools/lib/python2.7/site-packages/mozci/mozci.py", line 196, in _find_files
    job_status = _status_info(job_schedule_info)
  File "/Users/armenzg/venv/ci_tools/lib/python2.7/site-packages/mozci/mozci.py", line 189, in _status_info
    return buildjson.query_job_data(complete_at, request_id)
  File "/Users/armenzg/venv/ci_tools/lib/python2.7/site-packages/mozci/sources/buildjson.py", line 132, in query_job_data
    assert type(complete_at) is int
AssertionError

**Comment by armenzg** [comment]
Before we would *only* consider successful completed jobs.
We recently started considering failed and running jobs, hence, this bug appeared.

**Comment by adusca** [comment]
Running jobs will have 'complete_at: None', so they will always fail this assertion. We can stop considering running jobs, refactor query_job_data to be more running-job compatible or put the find_files part inside a try block.

**Comment by armenzg** [comment]
I agree with your approach to stop considering running jobs.
It is clean and as far as we know there isn't a way to do so.

**Comment by armenzg** [comment]
Alice fixed this in our previous release.
