### ISSUE TITLE
Remove --ignore E501 from tox

### ISSUE THREAD

**Issue by adusca** [armenzg/mozilla_ci_tools#242]
We are currently running flake8 with --ignore E501 [1]. We should remove this flag and fix the warnings this will cause [2]. 

[1] https://github.com/armenzg/mozilla_ci_tools/blob/master/tox.ini#L15

[2] 
mozilla_ci_tools[master $]$ flake8 mozci test
mozci/scripts/alltalos.py:66:101: E501 line too long (103 > 100 characters)
                        help="comma-separated substring filter indicating which jobs not to retrigger")
                                                                                                    ^
mozci/scripts/generate_triggercli.py:64:101: E501 line too long (106 > 100 characters)
        buglist = bugzilla.search_for.summary(options.test_name).keywords("intermittent-failure").search()
                                                                                                    ^
mozci/scripts/misc/find_status_for_jobs.py:66:101: E501 line too long (108 > 100 characters)
                    "&filter-resultStatus=success&filter-resultStatus=testfailed&filter-resultStatus=busted"
                                                                                                    ^
mozci/scripts/misc/find_status_for_jobs.py:67:101: E501 line too long (109 > 100 characters)
                    "&filter-resultStatus=exception&filter-resultStatus=retry&filter-resultStatus=usercancel"
                                                                                                    ^
mozci/scripts/misc/find_status_for_jobs.py:68:101: E501 line too long (109 > 100 characters)
                    "&filter-resultStatus=running&filter-resultStatus=pending&filter-resultStatus=coalesced")
                                                                                                    ^
mozci/utils/transfer.py:134:101: E501 line too long (127 > 100 characters)
            LOG.debug("The local file was last modified in %s. We need to delete the file and fetch it again." % last_mod_date)
                                                                                                    ^
mozci/mozci.py:172:101: E501 line too long (101 > 100 characters)
            LOG.info("We will trigger 1) '%s' instead of 2) '%s'" % (build_buildername, buildername))
                                                                                                    ^
mozci/mozci.py:173:101: E501 line too long (110 > 100 characters)
            LOG.info("We need to trigger the build job once (1) in order to be able to run the test job (2).")
                                                                                                    ^
mozci/mozci.py:364:101: E501 line too long (102 > 100 characters)
                LOG.info("In order to trigger %s %i times, please run the script again after %s ends."
                                                                                                    ^
mozilla_ci_tools[master $]$

**Comment by priyanklodha** [comment]
@adusca yup i would like to work on this. Please explain me how to proceed.

**Comment by armenzg** [comment]
@priyanklodha have you had a chance to review the initial comment by adusca?
You will need to checkout the mozilla ci tools repo and run flake8 as she mentioned.

**Comment by vaibhavmagarwal** [comment]
Hi @priyanklodha thanks for your interest. We need to shorten the line lengths to <=100 characters in various files. After locally downloading the repo, run 'flake8 mozci test --ignore E501' and you will know which lines to fix.

**Comment by adusca** [comment]
Fixed in #266
