### ISSUE TITLE
Raise less general Exceptions

### ISSUE THREAD

**Issue by adusca** [armenzg/mozilla_ci_tools#248]
We currently raise a lot of general 'Exceptions' [1]. Instead, we should raise more specific Exceptions (like in [2]). This would help with issue #191.

Steps to fix:
- create a new Exception class [3], it may be necessary to create more than one
- replace every 'raise Exception' with the appropriate 'raise {insert_new_exception_name_here}'

[1]
mozilla_ci_tools[master $%]$ grep -nR "raise Exception" *
mozci/platforms.py:127:        raise Exception("No build job found.")
mozci/mozci.py:204:        raise Exception("The status of the job is expected to have a "
mozci/mozci.py:267:        raise Exception("Repository name not found in buildername. "
mozci/sources/pushlog.py:101:        raise Exception('Unable to retrieve pushlog data. '
mozci/sources/buildapi.py:162:    raise Exception("Not implemented because of bug 1087336. Use "
mozci/sources/buildapi.py:224:            raise Exception("Unexpected status")
mozci/sources/buildapi.py:262:            raise Exception("That repository does not exist.")
mozci/scripts/trigger.py:110:        raise Exception(error_message)
mozci/scripts/generate_triggercli.py:116:        raise Exception('The script supports only for fx-team, mozilla-inbound, mozilla-aurora')
mozci/utils/transfer.py:89:                    raise Exception(
mozci/utils/transfer.py:165:            raise Exception("We received %s which is unexpected." % req.status_code)
mozilla_ci_tools[master]$ 

[2] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildjson.py#L166
[3] https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildjson.py#L22

**Comment by armenzg** [comment]
We should also consider turning "assert" statements into raise customized exceptions.
Good idea adusca!

**Comment by nikkisquared** [comment]
I'm working on this here https://github.com/nikkisquared/mozilla_ci_tools

**Comment by nikkisquared** [comment]
I've pushed my progress so far. I'd like any feedback for if I'm approaching this in the right way, or if not, what I can do differently.

**Comment by armenzg** [comment]
Commented on the PR.

**Comment by armenzg** [comment]
Fixed by @nikkisquared
