### ISSUE TITLE
Support 'tip' as a revision

### ISSUE THREAD

**Issue by adusca** [armenzg/mozilla_ci_tools#258]
mozci-triggerbyfilters REPO tip  should map to the tip revision of the repo

**Comment by adusca** [comment]
When we try passing 'tip' as a revision to mozci, it finds:
https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/tip?format=json

Weirdly, that finds a bunch of jobs like https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/request/53503722 (this one is from October 2014). I'm assuming it is a list of every job that was ever triggered by passing 'tip' as a revision to buildapi.

**Comment by armenzg** [comment]
https://github.com/armenzg/mozilla_ci_tools/pull/268
