### ISSUE TITLE
Pushlog should only be allowed to use json-pushes with push_id and not with changesets

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#26]
As per proper usage:
> Query by push ID, not by changeset or date.
http://mozilla-version-control-tools.readthedocs.org/en/latest/hgmo/pushlog.html#writing-agents-that-consume-pushlog-data

We currently do that in here:
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/pushlog.py#L40

**Comment by vaibhavmagarwal** [comment]
Yep, we should be able to do this by extracting pushid from query_revision_info and then calling query_pushid_range. I'll take this one.

**Comment by armenzg** [comment]
@indygreg We're trying to not use fromchange/tochange and instead use startID/endID

How does this change look to you?

**Comment by indygreg** [comment]
The "query by push ID" rule is meant for consumers wishing to iterate over available pushes. i.e. changeset discovery. This specific change doesn't make that much sense to me because it is turning 1 json-pushes HTTP request into 3. That feels like a regression to me.

**Comment by vaibhavmagarwal** [comment]
Ok, in that case @armenzg we should stick with current approach of calling pushlog once.

**Comment by armenzg** [comment]
Thank you @indygreg 
@vaibhavmagarwal my apologies for this. I should have asked gps first.
