### ISSUE TITLE
The JOBS_CACHE needs to implement invalidation

### ISSUE THREAD

**Issue by chmanchester** [armenzg/mozilla_ci_tools#274]
I noted in https://github.com/armenzg/mozilla_ci_tools/pull/257/files#r33635885 that our approach to the JOBS_CACHE would be problematic if we were running mozci from a long-running service. We need some sort of on-demand invalidation.

**Comment by vaibhavmagarwal** [comment]
This looks like a duplicate of https://github.com/armenzg/mozilla_ci_tools/issues/273 . Did you file it by mistake and should I close this?

**Comment by chmanchester** [comment]
Yeah, I lost network and github didn't give an indication the issue was submitted.
