### ISSUE TITLE
Evaluate the need for query_jobs_buildername

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#275]
As @chmanchester pointed out ( https://github.com/armenzg/mozilla_ci_tools/pull/257/files#r33635421 ), there may not be a need for query_jobs_buildername function anymore. Lets use this issue to track if it would be needed.

**Comment by vaibhavmagarwal** [comment]
Looks like query_jobs_buildername is used only in this file: https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/scripts/misc/find_logs_for_jobs.py#L25

Do people use it to find where the logs of files are located? I guess people can directly click on treeherder when they want to see a log of a job, so it isn't that useful.

**Comment by armenzg** [comment]
That script is under misc/ so we don't make promises that we will maintain them.
Those scripts are useful for experimentation and trying new things.

We might have lost the need of that function.
Remeber that with buildapi we take 2 steps to have accurate status.
* query_jobs_schedule() (from buildapi)
* query_job_data() (from buildjson)

We missed removed some of this query abilities in the mozci module; could you please follow up in here?

With t

**Comment by vaibhavmagarwal** [comment]
We still use query_jobs_schedule() and query_job_data() to get accurate data from buildapi. I think we do not need query_jobs_buildername function anymore, it really is not used in any major script or internally. Sent PR: https://github.com/armenzg/mozilla_ci_tools/pull/283

**Comment by armenzg** [comment]
Thanks @vaibhavmagarwal ! Happy to have cleaner code.
