### ISSUE TITLE
Display better error messages when user enters wrong credentials.

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#284]
I recently switched to a new machine, and entered wrong credentials while running mozci. It took me a while to figure out that my user email address was wrongly specified. MozCI can do a better job at this.

I will work on this issue.

**Comment by adusca** [comment]
I tried removing my user email and giving mozci a wrong one. I got this:
```
(venv)mozilla_ci_tools[master %]$ python mozci/scripts/trigger.py --dry-run --coalesced --repo-name mozilla-inbound -r tip
07/06/2015 07:51:35 INFO:	 The tip of mozilla-inbound is 6f7746225a61
Input Password: 
07/06/2015 07:51:37 CRITICAL:	 Your credentials were invalid
```

Is this what you are talking about? Maybe we could automatically remove invalid credentials (I had to 'rm ~/.mozilla/credentials.cfg' in order to make mozci work again).

**Comment by vaibhavmagarwal** [comment]
@adusca previously when you ran the script, it just gave an assertion error which wasn't helpful. So I have changed it to give the above error, which IMO is more helpful.
Regarding removing ~/.mozilla/credentials.cfg, I think that showing where the file is present and the value of user email is sufficient (like I have done in my patch) rather than removing the file because if the user email is correct, and the user enters just the password wrong (which can happen when user does not choose the save the password the first time), there is no need to delete the credentials file and make the user enter it again. That's why I haven't coded automatic removal of credentials.cfg, the user can change the file at the specified location, if he/she feels that the email is incorrect.

**Comment by adusca** [comment]
What happens when a wrong password is stored on the keyring? Is there an easy way for the user (or us) to remove it?

**Comment by vaibhavmagarwal** [comment]
You have raised a good point. Currently if the user stores a wrong password in the keyring, there is no good way, and the user has to manually delete the credentials files. So, there is a tradeoff here. Finally after thinking on this, I have come to the conclusion that it is better to delete the credential file and make the user enter (email, password) enter again, if there is an authentication problem.

**Comment by vaibhavmagarwal** [comment]
Fixed in https://github.com/armenzg/mozilla_ci_tools/pull/285/
