### ISSUE TITLE
Switch to new TravisCI infrastructure

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#301]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

Upcoming PR.

**Comment by vaibhavmagarwal** [comment]
Cool! This will reduce our wait times for travis builds to complete :)

**Comment by adusca** [comment]
Fixed in #302.
