### ISSUE TITLE
mozci-all-talos should respect try_by_default

### ISSUE THREAD

**Issue by Callek** [armenzg/mozilla_ci_tools#321]
I have a machine pool, which is only 1 machine, enabled on try, however it is try_by_default: False.  I noticed today that expected jobs didn't run, then I looked again and saw a wall of talos jobs that ran.

Glandium triggered jobs with mozci-alltalos and didn't even know my machine was available.

**Comment by vaibhavmagarwal** [comment]
This seems to be an issue with scheduling jobs. @armenzg is this something mozci can handle or is it more a configuration issue in buildbot?

**Comment by armenzg** [comment]
mozci-alltalos should respect the try syntax, however, we have currently not invested on parsing the try syntax.

@vaibhavmagarwal do you have time to add an exception for now for Win10 talos jobs?

**Comment by Callek** [comment]
specifically this is less an issue of parsing the try syntax, since whether or not it was -t all I wouldn't have expected win10 to run from it. I would expect it to run with -t all[Windows 10] though.  Or an explicit desire to run win10 via some mozci flag/command. But not "by default" when buildbot has try_by_default:False

**Comment by vaibhavmagarwal** [comment]
I think we can just deprecate all-talos.py and use triggerbyfilters.py (as in https://github.com/armenzg/mozilla_ci_tools/issues/206 ). triggerbyfilters.py  gives a proper list of jobs that will be triggered.
@jmaher do you have any issues if we remove alltalos.py script?

**Comment by jmaher** [comment]
+1 for removing alltalos.py

**Comment by vaibhavmagarwal** [comment]
With https://github.com/armenzg/mozilla_ci_tools/pull/331, win 10 talos jobs will not be triggered by default on try.
