### ISSUE TITLE
Contextless password prompt is confusing

### ISSUE THREAD

**Issue by gijsk** [armenzg/mozilla_ci_tools#327]
$ mozci-trigger -r 798b34311779 --repo-name try --existing-only -b 'mochitest'
    Input Password:

... password for what? This is really confusing, I don't know if it wants my LDAP password (for which account? how does it know that?) or a Persona login password of some kind (for which email address) or something else.

**Comment by armenzg** [comment]
Fair enough. LDAP indeed.

**Comment by armenzg** [comment]
Fixed in pull #330
