### ISSUE TITLE
Change does_builder_need_files() to is_downstream()

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#33]
Since we have recently introduced the concept of downstream and upstream builders.

If you think there is a better name than is_downstream() please let me know.
does_builder_need_files() have meant that if there is another builder that triggers this builder.
For instance, talos and test jobs are triggered by a build job.

https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/mozci.py#L243
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/platforms.py#L125

**Comment by valeriat** [comment]
Am I correct that this issue implies to simply rename the function?

**Comment by armenzg** [comment]
That is right. Probably adjusting some comments as well.
