### ISSUE TITLE
trigger all talos jobs - triggers old jobs which don't exist anymore

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#350]
we have disabled the talos other_nol64 and other_l64 jobs in place of just 'other'.  This was a few weeks ago and when scheduling jobs from treeherder via the |retrigger all talos jobs|, I get other_*64 jobs scheduled, but they cannot run.

Just this week we disabled all linux32 builders, and when calling |retrigger all talos jobs| I get linux32 jobs scheduled.

Can we have a better story for how mozci/pulse_actions handles expired builders?

**Comment by armenzg** [comment]
@vaibhavmagarwal can you help me understand the flow of how the retrigger all talos jobs code path works? I can help fix the code.

**Comment by vaibhavmagarwal** [comment]
@jmaher I see there are "other_nol64" like "Rev5 MacOSX Yosemite 10.10 try talos other_nol64" present in allthethings.json: https://secure.pub.build.mozilla.org/builddata/reports/allthethings.json
If they are disabled, should they be present in allthethings.json?
Trigger all talos jobs takes a list of talos jobs from allthethings.json itself that is why it is also triggering those jobs. We can blacklist those jobs if they cannot be removed from allthethings.json

**Comment by jmaher** [comment]
I see all the culprits in allthethings.json which looks to be generated from tools in the braindump repository.  maybe @armenzg knows how that is generated and what we can do to update it properly.

**Comment by armenzg** [comment]
This has been fixed.
We've added alerts to notice this sooner.
I'm looking into more reliable sources of allthethings.json or of better staleness detection.

You can generate the file with this:
https://wiki.mozilla.org/ReleaseEngineering/How_To/allthethings.json

Filed bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1210390
