### ISSUE TITLE
Attempting to backfill from Treeherder doesn't seem to be working for OSX bc7 jobs (possibly others)

### ISSUE THREAD

**Issue by KWierso** [armenzg/mozilla_ci_tools#351]
I've loaded https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&fromchange=32a9df806e46&group_state=expanded&filter-searchStr=os%20x%2010.%20mochitest%20mochitest%20browser%20chrome%20mochitest%20%28bc7&tochange=f39b2e477fbe in Treeherder and am trying to backfill those orange bc7 jobs. I select each one of the jobs and then select "backfill" from the bottom pane to try to fill in the gap between the orange and the last green job of that type. I've done that for each of those orange jobs, but no jobs have been scheduled to fill in that gap. (Note, I've now triggered a few of them manually via BuildAPI to get on with my day, so that's why there's some bc7 jobs in the gap.)

From my understanding, Treeherder's backfill button just emits pulse messages that mozci listens for to actually do the backfilling. As far as the Treeherder devs know, those pulse messages are being properly emitted (or at least, they aren't seeing any errors on NewRelic about them), so we're thinking it's a mozci issue.

Random guess: Is there some issue because the OS X builds are on 10.7, but the jobs are running on 10.6 and 10.10?

**Comment by armenzg** [comment]
Hi @KWierso thank you for reporting this.

@adusca already has a fixed for this in https://github.com/adusca/pulse_actions/pull/20

We will look into being alerted when this stops working in the future.

Our apologies for this disruption and thank you for filling it.

I'm closing this issue and filing it under pulse_actions which listens to the pulse messages:
https://github.com/adusca/pulse_actions/issues/21
https://wiki.mozilla.org/Auto-tools/Projects/Pulse_actions#Workflow

**Comment by vaibhavmagarwal** [comment]
I don't think this issue is related to https://github.com/adusca/pulse_actions/pull/20
On checking the logs I see:
```
Sep 30 19:51:47 pulse-actions app/worker2.1: INFO:	 backfill action requested by wkocher@mozilla.com on repo_name mozilla-inbound with job_id: 14988761 
Sep 30 19:51:49 pulse-actions app/worker2.1: INFO:	 We want to find a job for 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7' in this range: [ed34103d8978:10194aec7255] 
Sep 30 19:51:56 pulse-actions app/worker2.1: INFO:	 We only need to backfill [u'ed34103d8978', u'547905a13380', u'5cb68f2221bc', u'9b1ab8950c41', u'10194aec7255'] 
Sep 30 19:51:56 pulse-actions app/worker2.1: INFO:	 We want to have 1 job(s) of Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7 on revisions [u'ed34103d8978', u'547905a13380', u'5cb68f2221bc', u'9b1ab8950c41', u'10194aec7255'] 
Sep 30 19:51:56 pulse-actions app/worker2.1: INFO:	  
Sep 30 19:51:56 pulse-actions app/worker2.1: INFO:	 === ed34103d8978 === 
Sep 30 19:51:56 pulse-actions app/worker2.1: INFO:	 We want to have 1 job(s) of Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7 on revision ed34103d8978 
Sep 30 19:51:58 pulse-actions app/worker2.1: INFO:	 We have found 0 potential job(s) matching 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7' on ed34103d8978. We need to trigger more. 
Sep 30 19:51:58 pulse-actions app/worker2.1: INFO:	 ===> We want to trigger 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7' on revision 'ed34103d8978' a total of 1 time(s). 
Sep 30 19:51:58 pulse-actions app/worker2.1: INFO:	  
Sep 30 19:52:01 pulse-actions app/worker2.1: WARNING:	 Buildername Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7 is *NOT* valid. 
Sep 30 19:52:01 pulse-actions app/worker2.1: INFO:	 Check the file we just created builders.txt for a list of valid builders. 
Sep 30 19:52:01 pulse-actions app/worker2.1: ERROR:	 The builder Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7 requested is invalid 
```

So the buildername is invalid. Futher investigating and checking allthethings.json: https://secure.pub.build.mozilla.org/builddata/reports/allthethings.json
I can see that there is no 'Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7' buildername present in it. It seems like the buildername is present in Treeherder but not in allthethings.json. @armenzg can you see, why such a thing is happening?

**Comment by armenzg** [comment]
Looking at this.

**Comment by armenzg** [comment]
Filed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1210390

I used this instructions to generate it:
https://wiki.mozilla.org/ReleaseEngineering/How_To/allthethings.json

I definitely see the job on TH [1]
I don't see the job in the production allthethings.json [2] but I see it in the one I generated [3]
The size of the files are different [4]

[1] https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&filter-searchStr=rev5%20macosx%20yosemite%2010.10%20mozilla-inbound%20debug%20test%20mochitest-browser-chrome-7

[2]
armenzg@armenzg-thinkpad:~/repos/dump/community$ wget https://secure.pub.build.mozilla.org/builddata/reports/allthethings.json
armenzg@armenzg-thinkpad:~/repos/dump/community$ grep "Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7" allthethings.json 

[3]
armenzg@armenzg-thinkpad:~/repos/dump/community$ grep "Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7" ~/.mozilla/releng/repos/buildbot-configs/allthethings.json 
    "Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7": {
      "Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7", 
        "Rev5 MacOSX Yosemite 10.10 mozilla-inbound debug test mochitest-browser-chrome-7",

[4]
armenzg@armenzg-thinkpad:~/repos/dump/community$ ls -l allthethings.json 
-rw-rw-r-- 1 armenzg armenzg 11333972 Oct  1 09:55 allthethings.json
armenzg@armenzg-thinkpad:~/repos/dump/community$ ls -l ~/.mozilla/releng/repos/buildbot-configs/allthethings.json
-rw------- 1 armenzg armenzg 11811616 Oct  1 09:37 /home/armenzg/.mozilla/releng/repos/buildbot-configs/allthethings.json

**Comment by armenzg** [comment]
This has been fixed.
We've added alerts to notice this sooner.
I'm looking into more reliable sources of allthethings.json or of better staleness detection.
