### ISSUE TITLE
Store password if the developer requests it

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#359]

**Comment by vaibhavmagarwal** [comment]
@armenzg could you please provide more info for this issue? We currently ask the developer for storing the password in mozci

**Comment by armenzg** [comment]
My apologies.
I thought the PR would have been automatically been referenced:
https://github.com/armenzg/mozilla_ci_tools/pull/360

**Comment by armenzg** [comment]
Fixed in PR #360
