### ISSUE TITLE
Drop the need for --repo-name

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#39]
We currently specify --repo-name, however, we could simply extract it from the buildername.

Look at the various scripts under scripts/ and remove the need for it.

**Comment by vaibhavmagarwal** [comment]
Yes, we can easily do that and I have done it for one script. I will take this one.

**Comment by vaibhavmagarwal** [comment]
Fixed by https://github.com/armenzg/mozilla_ci_tools/pull/45/
