### ISSUE TITLE
If we try to find metadata for a job that run between 4pm-8pm sometime between 8-midnight we won't have data

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#46]
This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1135991
The gap appears as we get past 8pm. It widens until we hit midnight.
I don't know how to handle this. I will have to think about it.

We should at least warn the user until then rather than just saying we can't find the data:
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildjson.py#L57

**Comment by armenzg** [comment]
I will tackle this issue sometime during this week.

**Comment by armenzg** [comment]
I have provided a patch in https://bugzilla.mozilla.org/show_bug.cgi?id=1135991#c8
We are now waiting for a review.

**Comment by jmaher** [comment]
this is probably the same issue:

**Comment by jmaher** [comment]
This is probably the same issue:
https://pastebin.mozilla.org/8825713

assuming this gets fixed in releng, land, we still have to workaround this for the time being.  Can we patch mozci to deterine what timezone and work with it?  If this is deployed March 21, we will need to wait a couple of weeks prior to really being able to use mozci

**Comment by jmaher** [comment]
my local time is utc -5:00 (although daylight savings time could -4:00)

**Comment by armenzg** [comment]
The last 3 comments are not related to this issue but issue #135 

To rephrase this issue, we can only hit it this issue for jobs completed *today* between 4-5pm to 7-8pm and only if we run the script between 8pm and midnight. All pacific timezone.

We can't work around it unless we implemented fetching job information from treeherder which has been proven unreliable.

**Comment by armenzg** [comment]
The change was deployed. I will check tomorrow before closing this.

**Comment by armenzg** [comment]
The issue is almost 100% solved.
We now have a 15 minutes gap that only appears in the last 4 hours of the Pacific time from 4:45pm to 5pm.
This gets cleared after midnight.
I will also fix this issue.

**Comment by armenzg** [comment]
The last change was deployed.
