### ISSUE TITLE
Add coveralls support

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#51]
I can't mentor this since I don't know anything about it.
First of all, we don't have any coverage.
Second to this, adding coveralls support will help us when adding/fixing code and not regressing our coverage.

https://twitter.com/CoverallsApp/status/562351762049208320
https://github.com/mozilla/ship-it/pull/4
https://twitter.com/CoverallsApp/status/568441108360880129

**Comment by adusca** [comment]
I also don't know anything about it, but I would like to try. I th

**Comment by Callek** [comment]
Armen if not already done you probably want to enable it https://coveralls.io/repos/new

**Comment by armenzg** [comment]
Is this it?
https://coveralls.io/builds/2002456

**Comment by vaibhavmagarwal** [comment]
This is fixed!

**Comment by armenzg** [comment]
I backed out this until the TravisCI works again:
https://github.com/armenzg/mozilla_ci_tools/commit/f8f3200cd81c11ecdcba6f4736087229160052c0

**Comment by vaibhavmagarwal** [comment]
This is fixed in https://github.com/armenzg/mozilla_ci_tools/pull/66 :)
