### ISSUE TITLE
query_builders() and query_job_info() are not necessary for the normal operation of allthethings.py but for testing

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#53]
query_builders() and query_job_info() are not necessary for the normal operation of allthethings.py but for testing.

Let's move query_job_info() to test/test_platforms.py.
Let's drop query_builders() and use fetch_allthethings_data()

https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/allthethings.py#L106

**Comment by adusca** [comment]
I'll take this one.

**Comment by vaibhavmagarwal** [comment]
This is fixed in https://github.com/armenzg/mozilla_ci_tools/pull/55
