### ISSUE TITLE
Use autodoc for documenting the scripts

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#54]
I ended up putting the --help contents for each script under scripts.rst.

I would prefer if we figured it out how to use autodoc [1] to grab the script usage and description from the code rather than having it under scripts.rst.

I tried using it yesterday, however, I failed (unlike the modules under mozci/). There's something to figure out since scripts are a bit different than module. One of the steps that I believe were needed was to add scripts/__init__.py

I'm going to make scripts.rst be fully understandable (aka some more changes will land in the next two days), however, I will not be adding autodoc support.

[1] http://sphinx-doc.org/ext/autodoc.html#module-sphinx.ext.autodoc

**Comment by vaibhavmagarwal** [comment]
I am looking into this

**Comment by vaibhavmagarwal** [comment]
Ok, this is figured out in https://github.com/armenzg/mozilla_ci_tools/pull/58

**Comment by vaibhavmagarwal** [comment]
Fixed in https://github.com/armenzg/mozilla_ci_tools/pull/58
