### ISSUE TITLE
TravisCI is failing intermittently due to test_platforms.py

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#59]
It seems that since we started testing test_platforms.py we download bad allthethings.json or we timeout.

I think we either have to have a bigger timeout and/or some sort of retry logic for fetching allthethings.json. Maybe we want to commit a local copy for the tests.

For now, I have created a fix_tox_travis branch and merged the change into master until we fix this:
https://github.com/armenzg/mozilla_ci_tools/commit/8f2e3d3ccd2e09a1db681923e19b971bce5bd7b1

E   ValueError: Unterminated string starting at: line 39585 column 19 (char 1498245) [1]
E   ValueError: end is out of bounds [2]
E   ValueError: No JSON object could be decoded [3]

[1] https://travis-ci.org/armenzg/mozilla_ci_tools/builds/52321428#L319
[2] https://travis-ci.org/armenzg/mozilla_ci_tools/builds/52327344#L319
https://travis-ci.org/armenzg/mozilla_ci_tools/builds/52325309#L319

**Comment by vaibhavmagarwal** [comment]
I think we should be able to solve this. Basically, we can compare the content response (via Response.content) and the whole content length (via headers["Content-Length"]) and check if the whole file has downloaded, then only proceed forward. Also, use stream=true to download and save the content in chunks. I'll work on this.

:adusca has written some test for this, which is good from a unit-test approach, but a developer will need to download the actual file locally, so for the sake of solving this problem once and for all, better to do this on travis too.

**Comment by armenzg** [comment]
Let's try the streaming and re-enable the tests on a PR. Thanks!

**Comment by vaibhavmagarwal** [comment]
This should be fixed in https://github.com/armenzg/mozilla_ci_tools/pull/66/

Repoen, if still persists.
