### ISSUE TITLE
Merge trigger_range.py and trigger.py

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#61]
I think so, however, I want to hear how people feel about it.

I also wonder if generate_cli.py should have a more meaningful name.

**Comment by vaibhavmagarwal** [comment]
trigger.py and trigger_range.py share a lot of amount duplicate code. We can say trigger.py is just a special case of trigger_range.py in which delta=0. So ideally yes, we can merge them. But we will need to have to come up with a good name and documentation for the file that describes both scenarios.

I also agree that we can come up with a more meaningful name for generate_triggercli.py

**Comment by armenzg** [comment]
Thanks for giving me feedback.
I will deal with this since I'm trying to add another method of triggering.
I also want to have an "action" approach where we specify a word like "delta", "trigger-only", "range".

This way we can have less parameters and depending on the action we can expect different arguments.
Let's see if I get it right and make it cleaner.

**Comment by armenzg** [comment]
Fixed in https://github.com/armenzg/mozilla_ci_tools/commit/a8dd768c762b07f5fb2f220a49211d558a0d095b

I didn't do any changes with regards to actions.
