### ISSUE TITLE
Outputting a treeherder link from the scripts should be clickable

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#62]
In trigger_range.py we print the treeherder link.
We need to substitute the white spaces of the buildername for %20
Once that happens, we can click on the link from the console.

02/26/2015 04:24:09 INFO:	 https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&fromchange=b56e18c9dbfc&tochange=db9a70fc3230&filter-searchStr=Windows 7 32-bit mozilla-inbound opt test mochitest-1

**Comment by adusca** [comment]
I submitted PR 63 to fix this.

**Comment by vaibhavmagarwal** [comment]
This is fixed!
