### ISSUE TITLE
Create data structure to build an up-to-date trychooser

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#69]
Developers when they push to try, they need to add as part of their last commit a message that tells the CI what to trigger.
This syntax can be chosen through this UI:
http://trychooser.pub.build.mozilla.org

The problem with such UI is that it falls out of date and humans can have a lot of trouble to figure out even how to update it or what it missing.

I believe we could create a data structure which the UI could use to be built.
We should also use mozci/allthethings to generate that up-to-date data.

The code can be found in here:
http://hg.mozilla.org/build/tools/file/default/trychooser

**Comment by armenzg** [comment]
More or less, all of these bugs are related:
https://bugzilla.mozilla.org/showdependencytree.cgi?id=983802&hide_resolved=1

**Comment by adusca** [comment]
About bug https://bugzilla.mozilla.org/show_bug.cgi?id=1112777 :
platforms.py could have a function that returns a graph with all builders relations, or perhaps a  function that given a build job would return all its test jobs. Would that help? I can work on that.

**Comment by ahal** [comment]
Another consumer of this would be sfink's trychooser extension. It has a series of data structures:
https://bitbucket.org/sfink/trychooser/src/6f8e4db0f9a1065329ba5949eb2a27cc7965f98a/jobs.json?at=default

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1101548#c1

**Comment by armenzg** [comment]
adusca, fixing this might simple be creating one script that generates the data in something we agree. Not necessarily what we will ultimately end up using but at least in the right direction.
Once someone works on fixing the UI, we might need to adjust the script but at least we have a script to begin from.

Perhaps once we have some data, we can tinker with the the trychooser extension and see if we can feed from it.

I think the data could look like this:
       "linux":
              'default'; True,
              'debug_platform': 'linux-debug',
              'ubuntu32_vm': ["reftest", "reftest-e10s", ...],
              'ubuntu32_hw': ["chromez", ...]
       "linux-debug":
               'ubuntu32_vm': ["reftest", "reftest-e10s", ...],

Perhaps the UI for test side should look something like this:
                              linux-ubuntu32vm                           linux-debug
reftest               enabled checkbox     enabled checkbox
reftest-e10s      enabled checkbox     disabled checkbox
...
chromez            enabled checkbox    disabled checkbox

We would also have to deal with the subselection needed for "restrict tests to platforms"
e.g. -u none[Mulet Linux,Ubuntu,10.6,10.8,Windows XP,Windows 7,Windows 8,Android,b2g]

**Comment by adusca** [comment]
Ok, I'll work on this.

**Comment by adusca** [comment]
Some builders have 'ubuntu32_hw' as platform [1] and 'linux' as stage_platform, but others just have 'linux' as both [2]. We could have a heuristic to find the right platform, maybe matching shortnames with a list of known platforms. Or we could change allthethings.json to make 'platform' more useful.

We will also need a way of finding test type from the builder. Again we could do that with a heuristic or by changing allthethings.json.

[1]"Ubuntu HW 12.04 ash talos chromez": {
      "properties": {
        "branch": "ash", 
        "builddir": "ash_ubuntu32_hw_test-chromez", 
        "platform": "ubuntu32_hw", 
        "product": "firefox", 
        "repo_path": "projects/ash", 
        "script_repo_revision": "production", 
        "slavebuilddir": "test", 
        "stage_platform": "linux"
      }, 
      "shortname": "ash_ubuntu32_hw_test-chromez", 
      "slavebuilddir": "test", 
      "slavepool": "d9e951f02ea8ad5c0684376a23ddf73f212a4d6a"
    }, 

[2] "Ubuntu VM 12.04 ash debug test cppunit": {
      "properties": {
        "branch": "ash", 
        "platform": "linux", 
        "product": "firefox", 
        "repo_path": "projects/ash", 
        "script_repo_revision": "production", 
        "slavebuilddir": "test", 
        "stage_platform": "linux"
      }, 
      "shortname": "ash_ubuntu32_vm-debug_test-cppunit", 
      "slavebuilddir": "test", 
      "slavepool": "98a003047b25d49e082ba2ac30a21a89f982a204"
    },

**Comment by armenzg** [comment]
You gotta love buildbot configs :'(

It seems that talos jobs set different properties than test jobs.

We can see the correct value in her:
>  "shortname": "ash_ubuntu32_vm-debug_test-cppunit", 
>   "shortname": "ash_ubuntu32_hw_test-chromez", 

Test jobs are run on Amazon EC2 VMs while talos jobs run on hardware machines.

I think the right fix would be to adjust allthethings.json to produce the right data.
We might even want to add a "platforms" key with the other main keys (e.g. "builders", "schedulers", ...)

Alice, this issue is a bit of a pain so don't worry if you feel like stopping at any time. I bet there are other more pleasant issues to contribute to ;)

**Comment by armenzg** [comment]
Note that all the data that allthethings.json contains comes from the buildbot-configs.
Internally buildbot handles dependencies with platform keys like "linux64" even if the builders end up having a much longer name.
When the trychooser was designed, the choice was to let developers only use the platform keys regardless of which builders they would trigger.

Here's a bit more info:

Firefox Desktop and Firefox for Android *build* jobs:
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla/config.py

Firefox OS (aka b2g) build jobs:
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla/b2g_config.py

Test jobs:
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla-tests/config.py (It also has talos jobs)
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla-tests/mobile_config.py
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla-tests/b2g_config.py

Let's see for b2g, there are over 30 platforms (or build jobs):
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla/b2g_config.py#l24
A subset of them trigger a handful of test platforms:
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla-tests/b2g_config.py#l88

For Firefox desktop/mobile, there are over 20 platforms (or build jobs):
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla/config.py#l56

The interesting part about mobile/desktop is that is not a 1 to 1 relationship (like in b2g) but 1 build to many.
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla-tests/config.py#l108

For instance, the 'win32' build triggers 'xp-ix', 'win7-ix' and 'win8':
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla-tests/config.py#l134

In some cases both "slave_platforms" and "talos_slave_platforms" are the same but not always:
http://hg.mozilla.org/build/buildbot-configs/file/default/mozilla-tests/config.py#l162
For test jobs -> ubuntu32_vm
For talos jobs -> ubuntu32_hw
This is because we run performance jobs in real hardware while test jobs run on VMs.
For Mac and Windows everything runs on real hardware (for now).

**Comment by armenzg** [comment]
If we think about it, those keys can be extracted by modifying dump_master_json.py which is called by dump_allthethings.sh:
https://hg.mozilla.org/build/braindump/file/09c16abb129d/buildbot-related/dump_master_json.py
https://hg.mozilla.org/build/braindump/file/09c16abb129d/buildbot-related/dump_allthethings.sh

Commit script to generate allthethings.json:
https://hg.mozilla.org/build/braindump/file/09c16abb129d/community/generate_allthethings_json.sh

**Comment by armenzg** [comment]
The current data structure can be generated by running:
python scripts/misc/write_tests_per_platform_graph.py

These are the current bugs that need resolving:
https://bugzilla.mozilla.org/showdependencytree.cgi?id=983802&hide_resolved=1

**Comment by armenzg** [comment]
Let's close and let people who try to use the data helps us figure if there is anything else left.
