### ISSUE TITLE
ImportError: No module named mozci.mozci in readthedocs for scripts

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#74]
In readthedocs, the scripts section has an error:
ImportError: No module named mozci.mozci

http://mozilla-ci-tools.readthedocs.org/en/latest/scripts.html
So it is unable to find mozci module.

**Comment by vaibhavmagarwal** [comment]
With https://github.com/armenzg/mozilla_ci_tools/pull/84, some errors in mozci are gone, but this issue is still not fixed.

@armenzg, can you virtualenv, like specified here: http://read-the-docs.readthedocs.org/en/latest/faq.html

**Comment by armenzg** [comment]
I have the check for a virtualenv already enabled. It says "Install your project inside a virtualenv using setup.py install".

If I gave you admin power would you be able to give me a hand with this?

I think we can create a branch where we can experiment until we get this right.
We can enable the branch there.

**Comment by armenzg** [comment]
It also mentions about the requirements file.
Maybe all we need is to add a requirements.txt file or modify docs/requirements.txt.
However, I already see all dependencies being installed under the "install" section:
https://readthedocs.org/builds/mozilla-ci-tools/2390489/

I still see these errors:
WARNING: Unexpected return code 1 from command u'python ../scripts/trigger.py --help'
WARNING: Unexpected return code 1 from command u'python ../scripts/trigger_range.py --help'
WARNING: Unexpected return code 1 from command u'python ../scripts/generate_triggercli.py --help'

**Comment by vaibhavmagarwal** [comment]
I uploaded the mozilla_ci_tools in my own readthedocs account and found out that bin/ directory of rtd's virtualenv is not included in sys.path
This is a known open issue for them: https://github.com/rtfd/readthedocs.org/issues/814

There is a hack in which we can append the parent directory in sys.path. I tried that and you can see that the output is there: http://ci-tools.readthedocs.org/en/latest/scripts.html
Note, however for generate_triggercli.py it shows "No module named bugsy" which even though I have included in docs/requirements.txt ( https://readthedocs.org/builds/ci-tools/2392573/ ), confirms the fact that libraries in virtualenv are not included in system path.

So, in retrospect this is a bug on side of readthedocs, @armenzg how should we go about solving this? Remove program-output extension? (It may mean we will have to either search for another extension or again include the command line output as a string in the file).

**Comment by armenzg** [comment]
We could down the route of retracting from using program-output but I think you almost got it nailed.

I see that you're changing the sys.path inside of the script but perhaps can change it before calling 
Perhaps we can run temporarily add to program-output this to determine where we stand:
python -c "import sys; import pprint; pprint.pprint(sys.path)" && pip freeze

Perhaps we can simply go back to a simple approach where we mention in scripts.rst some info about the scripts, what you can do with them but simply direct them to try them out.

What do you think?

**Comment by vaibhavmagarwal** [comment]
I am also worried that it is unable to track 'bugsy' and I am unable to import it even by specifying in requirements.txt

**Comment by armenzg** [comment]
If their steps showed up on their logs we would know how to debug this.
I think the classic approach without the extension is best for now.

**Comment by vaibhavmagarwal** [comment]
Finally we decided to remove support from programoutput from sphinx. So this error no longer occurs. Closing this issue.
