### ISSUE TITLE
Add the ability to backfill

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#75]
We currently require sheriffs to use --start-revision and --end-revision.
This change will allow sheriffs to not have to worry about specifying an --end-revision but simply specify what is the starting bad revision.

We will also need to add a parameter to specify how many pushes back we should go.
We will default to a maximum of 20.

I'm taking this.

**Comment by vaibhavmagarwal** [comment]
We currently have --back-revisions to be specified (which is a number). So I think, you can a default=20 there, and have some adjustments to make this work. Should be easy :)

**Comment by vaibhavmagarwal** [comment]
--back-revisions is here: https://github.com/armenzg/mozilla_ci_tools/blob/master/scripts/trigger_range.py#L49

**Comment by armenzg** [comment]
Thanks for reminding me.

**Comment by vaibhavmagarwal** [comment]
np, currently it works with --rev and --back-revisions: https://github.com/armenzg/mozilla_ci_tools/blob/master/scripts/trigger_range.py#L77

You can edit it to make it --end-revisions, if you like... also remember to change the output in generate_triggercli.py in that case

**Comment by armenzg** [comment]
The backfill branch has a working solution.
Here are the various test cases being tested:
https://docs.google.com/a/mozilla.com/document/d/1NYhLDNcz4mlJolfxHeluVgQsuKBzIf8TTPGHpQ6qNjY

**Comment by armenzg** [comment]
I ended up not using --back-revisions since it made the code and conditions a bit harder.

**Comment by armenzg** [comment]
This was released as part of release 0.3.0
