### ISSUE TITLE
Add tests for documentation generation

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#79]
It seems like the documentation is now messed up [1] showing old content and bad left sidebars.
We should add a way to make sure that TravisCI and readthedocs notifies us.

[1] https://readthedocs.org/builds/mozilla-ci-tools/2385335
html
-----
WARNING: Unexpected return code 1 from command u'python ../scripts/trigger.py --help'
WARNING: Unexpected return code 1 from command u'python ../scripts/trigger_range.py --help'
WARNING: Unexpected return code 1 from command u'python ../scripts/generate_triggercli.py --help'
/home/docs/checkouts/readthedocs.org/user_builds/mozilla-ci-tools/checkouts/latest/docs/faq.rst:155: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/mozilla-ci-tools/checkouts/latest/docs/faq.rst:162: WARNING: Bullet list ends without a blank line; unexpected unindent.

**Comment by vaibhavmagarwal** [comment]
All the warnings here are now fixed (latest commit - https://github.com/armenzg/mozilla_ci_tools/pull/100 ).
Since these are warnings, rtd doesn't notify about this explicitly, but they it have in their logs.

**Comment by armenzg** [comment]
Happy with the current status. Thanks @vaibhavmagarwal
