### ISSUE TITLE
Remove checking exact caps for buildernames in mozci

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#82]
@jmaher has pointed out that, using mozci and copy pasting a buildername from treeherder fails due to caps. We should not check for exact case in mozci buildernames.

**Comment by armenzg** [comment]
Do you have an example?
I have needed to remove a white space from the beginning and end of a buildername but not the caps.

**Comment by adusca** [comment]
It makes sense, determine_upstream_builder is case sensitive.

**Comment by jmaher** [comment]
"ubuntu hw 12.04 x64 mozilla-inbound talos tp5o"

needs to be:
"Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o"

**Comment by vaibhavmagarwal** [comment]
03/04/2015 11:25:42 INFO:	 === 8477c9f45172 ===
03/04/2015 11:25:42 INFO:	 We want to have 4 job(s) of ubuntu HW 12.04 x64 mozilla-inbound talos tp5o on revision 8477c9f45172
03/04/2015 11:25:42 DEBUG:	 Determine if the revision is valid for buildapi.
03/04/2015 11:25:42 DEBUG:	 Determine repository associated to mozilla-inbound
03/04/2015 11:25:42 DEBUG:	 Loading /home/vaibhav/mozilla_ci_tools/scripts/repositories.txt
03/04/2015 11:25:42 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=8477c9f45172&full=1
03/04/2015 11:25:42 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 11:25:43 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=8477c9f45172&full=1 HTTP/1.1" 200 740
03/04/2015 11:25:43 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/04/2015 11:25:43 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/8477c9f45172?format=json
03/04/2015 11:25:43 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 11:25:46 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/8477c9f45172?format=json HTTP/1.1" 200 26009
03/04/2015 11:25:47 DEBUG:	 Find jobs matching 'ubuntu HW 12.04 x64 mozilla-inbound talos tp5o'
03/04/2015 11:25:47 INFO:	 We have found 0 job(s) of 'ubuntu HW 12.04 x64 mozilla-inbound talos tp5o'.
03/04/2015 11:25:47 DEBUG:	 We found 0 pending jobs, 0 running jobs and 0 successful_jobs.
03/04/2015 11:25:47 DEBUG:	 We have found 0 job(s) matching 'ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' on 8477c9f45172. We need to trigger more.
03/04/2015 11:25:47 INFO:	 We want to trigger 'ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' on revision '8477c9f45172' a total of 4 time(s).
03/04/2015 11:25:47 DEBUG:	 Determine if the revision is valid for buildapi.
03/04/2015 11:25:47 DEBUG:	 Determine repository associated to mozilla-inbound
03/04/2015 11:25:47 DEBUG:	 Loading /home/vaibhav/mozilla_ci_tools/scripts/repositories.txt
03/04/2015 11:25:47 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=8477c9f45172&full=1
03/04/2015 11:25:47 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 11:25:47 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=8477c9f45172&full=1 HTTP/1.1" 200 740
03/04/2015 11:25:47 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/04/2015 11:25:47 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 11:25:48 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
03/04/2015 11:25:49 WARNING:	 Buildername ubuntu HW 12.04 x64 mozilla-inbound talos tp5o is *NOT* valid.
03/04/2015 11:25:49 INFO:	 Check the file we just created builders.txt for a list of valid builders.
03/04/2015 11:25:49 ERROR:	 The builder ubuntu HW 12.04 x64 mozilla-inbound talos tp5o requested is invalid

**Comment by adusca** [comment]
I'm already working on this.

**Comment by armenzg** [comment]
I'm concerned with this.
I doubt we could actually trigger a job through with self-server/buildapi if we pass a buildername in lower case.

If we take the lower value string and turn into the real buildername then I'm OK with this.

**Comment by adusca** [comment]
The build jobs are unchanged. Only test jobs are lower cased. 

I tested locally with jmaher's example and it works.

**Comment by armenzg** [comment]
I think we fixed this in here:
https://github.com/armenzg/mozilla_ci_tools/commit/f2cec3cea9bc1b61aa514b3a24f07afb1ebd3e22
