### ISSUE TITLE
Failing to find a job

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#83]
I will work on it.

python trigger_range.py -b 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' --delta 4 --times 4 --rev f1134d7e0dab --debug --dry-run

03/04/2015 10:21:16 INFO:	 === ac621df2174a ===
03/04/2015 10:21:16 INFO:	 We want to have 4 job(s) of Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o on revision ac621df2174a
03/04/2015 10:21:16 DEBUG:	 Determine if the revision is valid for buildapi.
03/04/2015 10:21:16 DEBUG:	 Determine repository associated to mozilla-inbound
03/04/2015 10:21:16 DEBUG:	 Loading /home/armenzg/repos/ci_tools/scripts/repositories.txt
03/04/2015 10:21:16 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=ac621df2174a&tipsonly=1&full=1
03/04/2015 10:21:16 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 10:21:17 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=ac621df2174a&tipsonly=1&full=1 HTTP/1.1" 200 303
03/04/2015 10:21:17 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/04/2015 10:21:17 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/ac621df2174a?format=json
03/04/2015 10:21:17 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 10:21:17 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/ac621df2174a?format=json HTTP/1.1" 200 37460
03/04/2015 10:21:18 DEBUG:	 Find jobs matching 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o'
03/04/2015 10:21:18 DEBUG:	 We have found 1 job(s) of 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o'.
03/04/2015 10:21:18 DEBUG:	 We found 0 pending jobs, 0 running jobs and 1 successful_jobs.
03/04/2015 10:21:18 INFO:	 We have found 1 potential job(s) matching 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' on ac621df2174a. We need to trigger more.
03/04/2015 10:21:18 DEBUG:	 Loading /home/armenzg/repos/ci_tools/scripts/repositories.txt
03/04/2015 10:21:18 INFO:	 We want to trigger 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' on revision 'ac621df2174a' a total of 3 time(s).
03/04/2015 10:21:18 DEBUG:	 Determine if the revision is valid for buildapi.
03/04/2015 10:21:18 DEBUG:	 Determine repository associated to mozilla-inbound
03/04/2015 10:21:18 DEBUG:	 Loading /home/armenzg/repos/ci_tools/scripts/repositories.txt
03/04/2015 10:21:18 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=ac621df2174a&tipsonly=1&full=1
03/04/2015 10:21:18 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 10:21:18 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=ac621df2174a&tipsonly=1&full=1 HTTP/1.1" 200 303
03/04/2015 10:21:18 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/04/2015 10:21:18 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 10:21:24 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
03/04/2015 10:21:24 DEBUG:	 Buildername Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o is valid.
03/04/2015 10:21:24 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 10:21:24 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
03/04/2015 10:21:25 DEBUG:	 Buildername Linux x86-64 mozilla-inbound build is valid.
03/04/2015 10:21:25 DEBUG:	 Determine if the revision is valid for buildapi.
03/04/2015 10:21:25 DEBUG:	 Determine repository associated to mozilla-inbound
03/04/2015 10:21:25 DEBUG:	 Loading /home/armenzg/repos/ci_tools/scripts/repositories.txt
03/04/2015 10:21:25 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=ac621df2174a&tipsonly=1&full=1
03/04/2015 10:21:25 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 10:21:25 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=ac621df2174a&tipsonly=1&full=1 HTTP/1.1" 200 303
03/04/2015 10:21:25 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/04/2015 10:21:25 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/ac621df2174a?format=json
03/04/2015 10:21:25 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 10:21:26 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/ac621df2174a?format=json HTTP/1.1" 200 37550
03/04/2015 10:21:26 DEBUG:	 Find jobs matching 'Linux x86-64 mozilla-inbound build'
03/04/2015 10:21:26 DEBUG:	 We have found 1 job(s) of 'Linux x86-64 mozilla-inbound build'.
03/04/2015 10:21:26 DEBUG:	 List of matching jobs:
03/04/2015 10:21:26 DEBUG:	 {u'build_id': 64479653, u'status': 0, u'branch': u'integration/mozilla-inbound', u'buildername': u'Linux x86-64 mozilla-inbound build', u'claimed_by_name': u'buildbot-master70.bb.releng.use1.mozilla.com:/builds/buildbot/build1/master', u'buildnumber': 257, u'starttime': 1425408398, u'requests': [{u'complete_at': 1425409676, u'complete': 1, u'buildername': u'Linux x86-64 mozilla-inbound build', u'claimed_at': 1425409477, u'priority': 0, u'submittime': 1425408345, u'reason': u'scheduler', u'branch': u'integration/mozilla-inbound', u'request_id': 63335359, u'revision': u'ac621df2174afebd1530a2b1f731927ab996031b'}], u'endtime': 1425409674, u'revision': u'ac621df2174afebd1530a2b1f731927ab996031b'}
03/04/2015 10:21:26 DEBUG:	 We found a successful job. We don't search anymore.
03/04/2015 10:21:26 INFO:	 There is a _build_ job that has completed successfully.
03/04/2015 10:21:26 DEBUG:	 {u'build_id': 64479653, u'status': 0, u'branch': u'integration/mozilla-inbound', u'buildername': u'Linux x86-64 mozilla-inbound build', u'claimed_by_name': u'buildbot-master70.bb.releng.use1.mozilla.com:/builds/buildbot/build1/master', u'buildnumber': 257, u'starttime': 1425408398, u'requests': [{u'complete_at': 1425409676, u'complete': 1, u'buildername': u'Linux x86-64 mozilla-inbound build', u'claimed_at': 1425409477, u'priority': 0, u'submittime': 1425408345, u'reason': u'scheduler', u'branch': u'integration/mozilla-inbound', u'request_id': 63335359, u'revision': u'ac621df2174afebd1530a2b1f731927ab996031b'}], u'endtime': 1425409674, u'revision': u'ac621df2174afebd1530a2b1f731927ab996031b'}
03/04/2015 10:21:26 DEBUG:	 Job identified with complete_at value: 1425409676 run on 2015-03-03 UTC.
03/04/2015 10:21:26 DEBUG:	 The job completed at Tue, 03 Mar 2015 19:07:56 +0000 (UTC) (20 hours ago).
03/04/2015 10:21:31 DEBUG:	 We are going to look for 63335359 in builds-2015-03-03.js.
03/04/2015 10:21:31 ERROR:	 We have not found the job. If you see this problem please grep in builds-2015-03-03.js for 63335359 and run again with --debug and --dry-run.
Traceback (most recent call last):
  File "trigger_range.py", line 164, in <module>
    dry_run=options.dry_run
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 378, in trigger_range
    dry_run=dry_run)
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 300, in trigger_job
    buildername,
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 105, in _determine_trigger_objective
    files = _find_files(successful_job)
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 142, in _find_files
    job_status = buildjson.query_job_data(complete_at, request_id)
  File "/home/armenzg/repos/ci_tools/mozci/sources/buildjson.py", line 168, in query_job_data
    job = _find_job(request_id, builds, filename)
  File "/home/armenzg/repos/ci_tools/mozci/sources/buildjson.py", line 76, in _find_job
    "in %s for %d and run again with --debug and --dry-run." % (filename, request_id)
Exception: We have not found the job. If you see this problem please grep in builds-2015-03-03.js for 63335359 and run again with --debug and --dry-run

**Comment by adusca** [comment]
Weirdly, the same command works for me (on master, after PR #85): https://pastebin.mozilla.org/8824275

**Comment by armenzg** [comment]
I'm looking at this:
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=ac621df2174a&filter-searchStr=Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o
I see 4 jobs so I think we can't hit it anymore rather than being fixed by PR #85.
If we request --times 5 it hits the issue [2].

I'm going to fix this on my "backfill" branch since I will be merging that soon.

In the backfill branch if I run this [1] I won't hit the issues (--times 4).
If I run it with --times 5 I hit the issue [2]

[1] python trigger_range.py -b 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' --times 4 --rev ac621df2174a --debug --dry-run
[2]
03/04/2015 01:47:31 DEBUG:	 The job completed at Tue, 03 Mar 2015 19:07:56 +0000 (UTC) (23 hours ago).
03/04/2015 01:47:36 DEBUG:	 We are going to look for 63335359 in builds-2015-03-03.js.
03/04/2015 01:47:36 ERROR:	 We have not found the job. If you see this problem please grep in builds-2015-03-03.js for 63335359 and run again with --debug and --dry-run.
Traceback (most recent call last):
  File "trigger_range.py", line 164, in <module>
    dry_run=options.dry_run
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 378, in trigger_range
    dry_run=dry_run)
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 300, in trigger_job
    buildername,
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 105, in _determine_trigger_objective
    files = _find_files(successful_job)
  File "/home/armenzg/repos/ci_tools/mozci/mozci.py", line 142, in _find_files
    job_status = buildjson.query_job_data(complete_at, request_id)
  File "/home/armenzg/repos/ci_tools/mozci/sources/buildjson.py", line 168, in query_job_data
    job = _find_job(request_id, builds, filename)
  File "/home/armenzg/repos/ci_tools/mozci/sources/buildjson.py", line 76, in _find_job
    "in %s for %d and run again with --debug and --dry-run." % (filename, request_id)
Exception: We have not found the job. If you see this problem please grep in builds-2015-03-03.js for 63335359 and run again with --debug and --dry-run.

**Comment by armenzg** [comment]
I managed to fix this issue on "master".
We were using job["request_ids"] instead of job["properties"]["request_ids"]:
https://github.com/armenzg/mozilla_ci_tools/commit/87c32cb126f0ccf4f606c45c7461f84cff881204

I have also added a script under misc/ to help us understand this better in the near future.

Both of these commands work:
python scripts/trigger_range.py -b 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' --times 4 --rev ac621df2174a --debug --dry-run
python scripts/trigger_range.py -b 'Ubuntu HW 12.04 x64 mozilla-inbound talos tp5o' --times 5 --rev ac621df2174a --debug --dry-run

**Comment by armenzg** [comment]
@jmaher Your reported issue has been fixed on master.
