### ISSUE TITLE
coalesced jobs are viewed as completed jobs

### ISSUE THREAD

**Issue by jmaher** [armenzg/mozilla_ci_tools#87]
03/04/2015 12:48:04 INFO:	 
03/04/2015 12:48:04 INFO:	 === 7ad48d9fb454 ===
03/04/2015 12:48:04 INFO:	 We want to have 4 job(s) of Windows XP 32-bit mozilla-inbound talos g1 on revision 7ad48d9fb454
03/04/2015 12:48:04 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 12:48:05 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 12:48:06 INFO:	 We have found 1 job(s) of 'Windows XP 32-bit mozilla-inbound talos g1'.
03/04/2015 12:48:06 INFO:	 We want to trigger 'Windows XP 32-bit mozilla-inbound talos g1' on revision '7ad48d9fb454' a total of 3 time(s).
03/04/2015 12:48:06 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 12:48:06 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 12:48:07 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 12:48:08 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/04/2015 12:48:08 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 12:48:09 INFO:	 We have found 1 job(s) of 'WINNT 5.2 mozilla-inbound build'.
03/04/2015 12:48:09 INFO:	 There is a job that has completed successfully.
03/04/2015 12:48:15 INFO:	 Starting new HTTP connection (1): ftp.mozilla.org
03/04/2015 12:48:15 INFO:	 Starting new HTTP connection (1): ftp.mozilla.org
03/04/2015 12:48:15 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 12:48:16 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 12:48:17 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/04/2015 12:48:17 INFO:	 

this job is coalesced and never ran.

that is part of the output from:
python trigger_range.py -b "Windows XP 32-bit mozilla-inbound talos g1" --rev 7ad48d9fb454 --delta 3 --times 4

**Comment by armenzg** [comment]
I see what you're saying. You want 4 talos jobs but only 3 show up.
There is not a coalesced job according to treeherder [1].

I will look at the code that calculate how many jobs we have.

> 03/04/2015 04:05:07 INFO:	 We want to have 4 job(s) of Windows XP 32-bit mozilla-inbound talos g1 on revision 7ad48d9fb454
> 03/04/2015 04:05:09 INFO:	 We have found 4 job(s) of 'Windows XP 32-bit mozilla-inbound talos g1'.

[1]
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&revision=7ad48d9fb454&filter-searchStr=Windows XP 32-bit mozilla-inbound talos g1&filter-resultStatus=success&filter-resultStatus=testfailed&filter-resultStatus=busted&filter-resultStatus=exception&filter-resultStatus=retry&filter-resultStatus=usercancel&filter-resultStatus=running&filter-resultStatus=pending&filter-resultStatus=coalesced

**Comment by armenzg** [comment]
As far as I can tell, my code is showing reality. treeherder is not.

If you load this:
https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/7ad48d9fb454
and search for "windows xp 32-bit mozilla-inbound talos g1" you will see four jobs with four different start and end times.

I have filed bug 1139664.

**Comment by jmaher** [comment]
thanks for looking into this.  I believe that coalesced jobs are scheduled
with a start/endtime, but there is a way to determine it.  I don't see logs
anywhere on ftp for the results though (look for talos svgr as I had
triggered g1)

**Comment by armenzg** [comment]
We now account for coalesced jobs properly:
https://github.com/armenzg/mozilla_ci_tools/commit/fed7a85b660169e9b6cb82513fc87874c520beca
