### ISSUE TITLE
If we need to trigger a downstream job multiple times, do not trigger its upstream job multiple times

### ISSUE THREAD

**Issue by vaibhavmagarwal** [armenzg/mozilla_ci_tools#90]
I used this command: python trigger_range.py -b="Windows 8 64-bit mozilla-inbound pgo talos svgr" --rev=6470d649e1bb --from-rev=60a37ae57d9c --times=4 --debug

and the corresponding output:
03/06/2015 12:33:46 INFO:	 === a1a89ff4ee31 ===
03/06/2015 12:33:46 INFO:	 We want to have 4 job(s) of Windows 8 64-bit mozilla-inbound pgo talos svgr on revision a1a89ff4ee31
03/06/2015 12:33:46 DEBUG:	 Determine if the revision is valid for buildapi.
03/06/2015 12:33:46 DEBUG:	 Determine repository associated to mozilla-inbound
03/06/2015 12:33:46 DEBUG:	 Loading /home/vaibhav/mozilla_ci_tools/scripts/repositories.txt
03/06/2015 12:33:46 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=a1a89ff4ee31&tipsonly=1&full=1
03/06/2015 12:33:46 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/06/2015 12:33:46 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=a1a89ff4ee31&tipsonly=1&full=1 HTTP/1.1" 200 290
03/06/2015 12:33:46 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/06/2015 12:33:46 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/a1a89ff4ee31?format=json
03/06/2015 12:33:46 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:47 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/a1a89ff4ee31?format=json HTTP/1.1" 200 27429
03/06/2015 12:33:48 DEBUG:	 Find jobs matching 'Windows 8 64-bit mozilla-inbound pgo talos svgr'
03/06/2015 12:33:48 DEBUG:	 We have found 0 job(s) of 'Windows 8 64-bit mozilla-inbound pgo talos svgr'.
03/06/2015 12:33:48 DEBUG:	 We found 0 pending jobs, 0 running jobs and 0 successful_jobs.
03/06/2015 12:33:48 INFO:	 We have found 0 potential job(s) matching 'Windows 8 64-bit mozilla-inbound pgo talos svgr' on a1a89ff4ee31. We need to trigger more.
03/06/2015 12:33:48 DEBUG:	 Loading /home/vaibhav/mozilla_ci_tools/scripts/repositories.txt
03/06/2015 12:33:48 INFO:	 We want to trigger 'Windows 8 64-bit mozilla-inbound pgo talos svgr' on revision 'a1a89ff4ee31' a total of 4 time(s).
03/06/2015 12:33:48 DEBUG:	 Determine if the revision is valid for buildapi.
03/06/2015 12:33:48 DEBUG:	 Determine repository associated to mozilla-inbound
03/06/2015 12:33:48 DEBUG:	 Loading /home/vaibhav/mozilla_ci_tools/scripts/repositories.txt
03/06/2015 12:33:48 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=a1a89ff4ee31&tipsonly=1&full=1
03/06/2015 12:33:48 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/06/2015 12:33:49 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=a1a89ff4ee31&tipsonly=1&full=1 HTTP/1.1" 200 290
03/06/2015 12:33:49 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/06/2015 12:33:49 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:49 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
03/06/2015 12:33:50 DEBUG:	 Buildername Windows 8 64-bit mozilla-inbound pgo talos svgr is valid.
03/06/2015 12:33:50 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:50 DEBUG:	 "HEAD /builddata/reports/allthethings.json HTTP/1.1" 200 0
03/06/2015 12:33:51 DEBUG:	 Buildername WINNT 6.1 x86-64 mozilla-inbound pgo-build is valid.
03/06/2015 12:33:51 DEBUG:	 Determine if the revision is valid for buildapi.
03/06/2015 12:33:51 DEBUG:	 Determine repository associated to mozilla-inbound
03/06/2015 12:33:51 DEBUG:	 Loading /home/vaibhav/mozilla_ci_tools/scripts/repositories.txt
03/06/2015 12:33:51 DEBUG:	 About to fetch https://hg.mozilla.org/integration/mozilla-inbound/json-pushes?changeset=a1a89ff4ee31&tipsonly=1&full=1
03/06/2015 12:33:51 INFO:	 Starting new HTTPS connection (1): hg.mozilla.org
03/06/2015 12:33:52 DEBUG:	 "GET /integration/mozilla-inbound/json-pushes?changeset=a1a89ff4ee31&tipsonly=1&full=1 HTTP/1.1" 200 290
03/06/2015 12:33:52 DEBUG:	 Requesting the info with full=1 can yield too much unecessary output to debug anything properly
03/06/2015 12:33:52 DEBUG:	 About to fetch https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/a1a89ff4ee31?format=json
03/06/2015 12:33:52 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:52 DEBUG:	 "GET /buildapi/self-serve/mozilla-inbound/rev/a1a89ff4ee31?format=json HTTP/1.1" 200 27429
03/06/2015 12:33:53 DEBUG:	 Find jobs matching 'WINNT 6.1 x86-64 mozilla-inbound pgo-build'
03/06/2015 12:33:53 DEBUG:	 We have found 0 job(s) of 'WINNT 6.1 x86-64 mozilla-inbound pgo-build'.
03/06/2015 12:33:53 DEBUG:	 List of matching jobs:
03/06/2015 12:33:53 INFO:	 We are going to trigger WINNT 6.1 x86-64 mozilla-inbound pgo-build instead of Windows 8 64-bit mozilla-inbound pgo talos svgr
03/06/2015 12:33:53 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:54 DEBUG:	 "POST /buildapi/self-serve/mozilla-inbound/builders/WINNT%206.1%20x86-64%20mozilla-inbound%20pgo-build/a1a89ff4ee31 HTTP/1.1" 202 77
03/06/2015 12:33:54 DEBUG:	 We have received this request:
03/06/2015 12:33:54 DEBUG:	  - status code: 202
03/06/2015 12:33:54 DEBUG:	  - text:        {
  "status": "OK",
  "request_id": 1195858
}
03/06/2015 12:33:54 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:54 DEBUG:	 "POST /buildapi/self-serve/mozilla-inbound/builders/WINNT%206.1%20x86-64%20mozilla-inbound%20pgo-build/a1a89ff4ee31 HTTP/1.1" 202 77
03/06/2015 12:33:54 DEBUG:	 We have received this request:
03/06/2015 12:33:54 DEBUG:	  - status code: 202
03/06/2015 12:33:54 DEBUG:	  - text:        {
  "status": "OK",
  "request_id": 1195859
}
03/06/2015 12:33:54 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:55 DEBUG:	 "POST /buildapi/self-serve/mozilla-inbound/builders/WINNT%206.1%20x86-64%20mozilla-inbound%20pgo-build/a1a89ff4ee31 HTTP/1.1" 202 77
03/06/2015 12:33:55 DEBUG:	 We have received this request:
03/06/2015 12:33:55 DEBUG:	  - status code: 202
03/06/2015 12:33:55 DEBUG:	  - text:        {
  "status": "OK",
  "request_id": 1195860
}
03/06/2015 12:33:55 INFO:	 Starting new HTTPS connection (1): secure.pub.build.mozilla.org
03/06/2015 12:33:56 DEBUG:	 "POST /buildapi/self-serve/mozilla-inbound/builders/WINNT%206.1%20x86-64%20mozilla-inbound%20pgo-build/a1a89ff4ee31 HTTP/1.1" 202 77
03/06/2015 12:33:56 DEBUG:	 We have received this request:
03/06/2015 12:33:56 DEBUG:	  - status code: 202
03/06/2015 12:33:56 DEBUG:	  - text:        {
  "status": "OK",
  "request_id": 1195861
}
03/06/2015 12:33:56 DEBUG:	 Loading /home/vaibhav/mozilla_ci_tools/scripts/repositories.txt
03/06/2015 12:33:56 INFO:	 https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound&fromchange=6470d649e1bb&tochange=a1a89ff4ee31&filter-searchStr=Windows+8+64-bit+mozilla-inbound+pgo+talos+svgr
(venv)vaibhav@vaibhav:~/mozilla_ci_tools/scripts(master) $ python trigger_range.py -b="Windows 8 64-bit mozilla-inbound pgo talos svgr" --rev=6470d649e1bb --from-rev=60a37ae57d9c --times=4 --debug

**Comment by vaibhavmagarwal** [comment]
Now the build was not present for this job, so it should have triggered the build once, but it did 4 times
https://secure.pub.build.mozilla.org/buildapi/self-serve/mozilla-inbound/rev/a1a89ff4ee31
(Need try credentials to access it)

**Comment by armenzg** [comment]
I fixed this issue with this:
https://github.com/armenzg/mozilla_ci_tools/commit/d538e466ee4af69f8f7b7d09657efb41e27af9b0

Specifically this line:
https://github.com/armenzg/mozilla_ci_tools/commit/d538e466ee4af69f8f7b7d09657efb41e27af9b0#diff-fceb32314e6c82e12ca12ab409d93d8aR325

The rest was mere refactoring.
