### ISSUE TITLE
Read less repositories.txt

### ISSUE THREAD

**Issue by armenzg** [armenzg/mozilla_ci_tools#94]
Every time we want to determine repo_name based on a buildername we end up calling query_repositories().
https://github.com/armenzg/mozilla_ci_tools/blob/master/mozci/sources/buildapi.py#L138

We cache repositories.txt so we don't hit buildapi often and reduce latency.
However, I believe that even reading from disk often is bad.

I was thinking of designing a class that can have the knowledge of the contents of repositories.txt and every time we query it, regardless from which module, we will be able to read the values from memory rather than disk.

Running any script with --debug (You can use --dry-run) should only log once that we're reading from repositories.txt.

**Comment by adusca** [comment]
I would like to work on this.

**Comment by armenzg** [comment]
Thank you Alice!

**Comment by armenzg** [comment]
https://github.com/armenzg/mozilla_ci_tools/pull/105
